### ISSUE TITLE
Quick Test Steps

### ISSUE THREAD

**Issue by jlpoolen** [thirtythreeforty/neolink#11]
I successfully built the server in Gentoo and have it running and connect to a single camera.
I'm gated at what to use to connect to the neolink server to verify.

I tried VLC on the same machine as the server is running, a laptop, and then in VLC: Media->Open Network Stream [Cntrl-N] and entered:

    rtsp://localhost:8554

I have been out of touch with streaming videos for over a year, it would be helpful to have instructions on how to easily test with VLC whether a stream is working.  And if you have multiple cameras as the example configuration file has, one probably has to specify it in the URL to VLC?

Can you provide some instructions for a quick assay?

Realize people might come to this project out of the video streaming arena and test it, so what may seem second nature to you may be a stumbling block -- my problem is a case in point.  Once I've verified this is working, then I'll dive deeper into the protocols, so helping someone out of the blue try this out so they can actually see the results goes a long way.  Also, I was interested in Shinobi, until I studied his licensing and walked away from it.  And Blue Iris is proprietary.  So that leaves VLC for testing single streams, yes?

**Comment by jlpoolen** [comment]
I see now I should have appended a forward slash and the name of the camera as specified in the configuration file.  So, I tried on my Windows workstation using VLC the following URL:

     rtsp://ares:8554/garage_east

My configuration file naming "garage_east" is attached as jlpoole.toml

[jlpoole.toml.txt](https://github.com/thirtythreeforty/neolink/files/4659724/jlpoole.toml.txt)

I was not successful in displaying any video in VLC; however, things were happening and I'll log matters and then update this issue.
Aside from a generic assay, please stand by and I'll provide specifics and logs.

**Comment by thirtythreeforty** [comment]
Hey thanks for trying this out. You're right, the getting-started directions could definitely be better.  Your configuration file looks good; the camera's address should definitely end in `:9000` (as that's the default Baichuan port).  It might be good for me to add a default here.

So - In my experience VLC has had issues with the stream from the B800, because the key frames are so large they fill the UDP receive buffer.  Blue Iris and `ffplay` both handle this correctly if you give the correct options.

Give me a little while and I'll fish out the ffplay command I was using.

**Comment by thadius83** [comment]
I'm working on getting some install instructions and processes for several people from FB who've reached out..

VLC does not work well with it at all, either in windows or ubuntu.

Unrefined install instructions for windows.
1. Download the following items.
	a. Prebuilt Neolink Client
	b. Gstreamer from https://gstreamer.freedesktop.org/data/pkg/windows/1.16.2/gstreamer-1.0-msvc-x86_64-1.16.2.msi
2. Install Gstreamer from the above installed MSI
	a. You may get a warning from Windows, as Gstreamer is unsigned, click more info, and "run anyway"
	b. Next
	c. Accept Licence & Next
	d. Select Typical
	e. Install 
	f. Accept the Windows UAC prompt.
Gstreamer is now installed

<<Pause>>
Two options from here.

<<option 1>>
3. Copy the Neolink.exe, and Config file to the Gstreamer Install Directory "C:\gstreamer\1.0\x86_64\bin" if left as default.
	a. Once in this folder, edit the config file, to add your cameras
	b. the "name" will make up the URL of your RTSP feed i.e rtsp://10.0.0.x:8554/test
	c. Run the following commands from a windows command prompt
		"Cd gstreamer\1.0\x86_64\bin" <enter>
		neolink --config file.config 
4. create shortcut / script etc to add to auto startup
5. Connect your software NVR to the new cameras RTS url's rtsp://10.0.0.x:8554/test, rtsp://10.0.0.x:8554/test1, etc, you may need to adjust your windows firewall if not hosted on the same machine.

6. To troubleshoot or for more output, before launching, within the windows command window input one of the following 
set RUST_LOG=verbose
set RUST_LOG=debug
set RUST_LOG=info
set RUST_LOG=warn
set RUST_LOG=error


<<Option 2>>
Open a command prompt
set path "%path%;c:\gstreamer\1.0\x86_64\bin"    <- or where-ever you installed gstreamer
copy the neolink application and config file to desired location.

3. Copy the Neolink.exe, and Config file to desired location
	a. Once in this folder, edit the config file, to add your cameras
	b. the "name" will make up the URL of your RTSP feed i.e rtsp://10.0.0.x:8554/test
	c. Run the following commands from a windows command prompt
		set path "%path%;c:\gstreamer\1.0\x86_64\bin"    <- or where-ever you installed gstreamer
		neolink --config file.config 
4. create shortcut / script etc to add to auto startup
5. Connect your software NVR to the new cameras RTS url's rtsp://10.0.0.x:8554/test, rtsp://10.0.0.x:8554/test1, etc, you may need to adjust your windows firewall if not hosted on the same machine.

6. To troubleshoot or for more output, before launching, within the windows command window input one of the following 
set RUST_LOG=verbose
set RUST_LOG=debug
set RUST_LOG=info
set RUST_LOG=warn
set RUST_LOG=error


A more refined install process is forthcoming.

**Comment by thirtythreeforty** [comment]
That's pretty much correct, and there are a disappointing number of steps there :)

I really appreciate the documentation. If you send a PR I would gladly take it.

I am also going to package as a real installer (see #1) so hopefully the discussion will be limited to "how to write a config file."

**Comment by thadius83** [comment]
Apologies I missed the installer part :)

**Comment by doneldanderson** [comment]
Just found these additional instructions, very helpful. Searching all over for the precompiled neolink.exe file and I am having trouble locating it. Is it on github?

**Comment by thirtythreeforty** [comment]
Yes - if you click on [the link to the GitHub Actions CI](https://github.com/thirtythreeforty/neolink/actions?query=branch%3Amaster) (it's also in the readme, but it's easy to miss), you get a list of changes I've made. If you click on the topmost (recent) one you get a list of precompiled files for Windows and Ubuntu Linux. Click one of those.

I'm gonna modify the readme to add better directions.

**Comment by thirtythreeforty** [comment]
Addressed in 452c2372361eb3e6427d3fa5b58425bcd0531aa9. Could you give it a read and see if that's sufficient?

**Comment by doneldanderson** [comment]
Yes, new instructions helped immensely and I got the feeds all working.

This is great!

**Comment by thirtythreeforty** [comment]
Awesome. Glad it's working! Hopefully putting an installer together will finish easing the setup. I'll close this but feel free to reopen if you have other questions.

**Comment by 02powerstroke** [comment]
I am having issues getting my cameras to connect. I have installed gstreamer and moved the neolink.exe and config file to the folder structure. When I try to connect to the B800 camera, it is struggling. Any ideas? Below is my config text.  

bind = "0.0.0.0"

[[cameras]]
name = "http://192.168.1.214:9000"
username = "admin"
password = ""
address = "192.168.1.214:9000"

**Comment by hh1209** [comment]
@02powerstroke

First, try deleting the port (":9000") from the camera's IP address, so just 'address = 192.168.1.214"'.

I would also change the camera name to something phonetic like 'garagedoor' or something.

Try that and let me know what happens.

________________________________

**Comment by 02powerstroke** [comment]
Tried that and ended up with the following;

[2020-07-08T01:48:31Z INFO  neolink] Neolink 0.3.0 (unknown commit) release
Error: ConfigError(Error { inner: ErrorInner { kind: Custom, line: Some(6), col: 10, at: Some(86), message: "invalid IP address syntax", key: ["cameras", "address"] } })

**Comment by hh1209** [comment]
Sorry, the port is supposed to be there. Could you send the output with the port back on the IP address?

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by 02powerstroke** [comment]
Not sure I follow what you are asking. Below is the output that typically comes when I attempt to use the IP and port. 

[2020-07-08T02:04:05Z INFO  neolink] cam9: Connecting to camera at 192.168.1.214:9000
[2020-07-08T02:04:05Z INFO  neolink] cam9: Connecting to camera at 192.168.1.214:9000
[2020-07-08T02:04:05Z INFO  neolink] cam9: Connected to camera, starting video stream mainStream
[2020-07-08T02:04:05Z INFO  neolink] cam9: Connected to camera, starting video stream subStream
[2020-07-08T02:04:06Z ERROR neolink] Error streaming from camera cam9, will retry in 1s: Timeout
[2020-07-08T02:04:06Z ERROR neolink] Error streaming from camera cam9, will retry in 1s: Timeout

**Comment by hh1209** [comment]
Are you using WiFi or Ethernet to connect to the camera?

Also are there any other devices streaming from the cameras? NVRs, Reolink Apps?

**Comment by 02powerstroke** [comment]
cameras are tied in direct to a POE switch. I tried closing the Reolink app, but it didn't have an impact.

**Comment by hh1209** [comment]
Are the times set on the cameras? You can check that in the Reolink App.

Also, check if your cameras are updated to the latest firmware version.

**Comment by 02powerstroke** [comment]
set the times and that seemed to help. Still not getting a feed to show up in Blue Iris though.

**Comment by hh1209** [comment]
So in Blue Iris, make sure your "recieve buffer" is set to 20MB.

The cameras have stopped timing out now, correct?

**Comment by 02powerstroke** [comment]
correct; Now the live streams are active, but I can't seem to get them to feed into Blue iris. I changed to buffer to 20mb.

**Comment by hh1209** [comment]
Try making your BI Setup match this for your cameras.

![BISetup](https://user-images.githubusercontent.com/54970289/86868400-3c74b700-c09a-11ea-99c5-5a51b03ae290.JPG)

**Comment by 02powerstroke** [comment]
I get "RTSP 404 Not found"

**Comment by hh1209** [comment]
It takes a second for BI to pick it up. Is it working smoothly?

**Comment by 02powerstroke** [comment]
It is! Thank you! Is the RSTP stream from Neolink going to always use 127.0.0.1:8554?

**Comment by hh1209** [comment]
No problem.

Yes, for each camera you use, you'll use that address, and just change the path to each camera.

**Comment by 02powerstroke** [comment]
Woot! Thank you!!

**Comment by hh1209** [comment]
No problem, glad you got it working. 

I'd turn off auto reboot on the cameras if you want to keep it working. Rebooting the cameras causes the time settings to be cleared, then Neolink will start timing out.

**Comment by 02powerstroke** [comment]
that's good to know. Does this also allow the use of audio?

**Comment by hh1209** [comment]
As of yet, Neolink does not support an audio feed. That is in the works.

**Comment by 02powerstroke** [comment]
sounds great. Thanks again!
