### ISSUE TITLE
Question for Reolink-Lumus

### ISSUE THREAD

**Issue by SR84** [thirtythreeforty/neolink#110]
Lumus doenst support FTP Upload. The Camera still records the video on its SD-Card.

I am searching for a possibility to download the video files programmatically.

I havent searched in your code. Do you know, if its possible?

Greetings from Germany,
Sebastian

**Comment by QuantumEntangledAndy** [comment]
we don't currently have the functionality to pull the recorded videos on the camera. It is certainly possible and can be added. One day I hope we can match all functionalty of the official client and more. But there a long todo list haha.

In the mean time what this program can do is provide an rtsp stream of the camera. From this stream you can use standard tool to record to your video locally.

**Comment by SR84** [comment]
Thanks for your comment.

I only want to store the video files on my nas drive programmatically. 

By the way, keep up your good work. Thank you.
