### ISSUE TITLE
Ubuntu Server 20.04: method DESCRIBE failed: 503 Service Unavailable

### ISSUE THREAD

**Issue by richardklingler** [thirtythreeforty/neolink#117]
**Describe the bug**
Running neolink on Debian 10.7 is fine..and ffprobe reports correctly:

Input #0, rtsp, from 'rtsp://10.0.60.2:8554/lager':
  Metadata:
    title           : Session streamed with GStreamer
    comment         : rtsp-server
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1440, 90k tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_s16be, 16000 Hz, 1 channels, s16, 256 kb/s

But when running neolink on Ubuntu Server 20.04:

[rtsp @ 0x55bd821dbf00] method DESCRIBE failed: 503 Service Unavailable
rtsp://127.0.0.1:8554/lager: Server returned 5XX Server Error reply
root@shinobi:/home/klingler# ffprobe rtsp://127.0.0.1:8554/lager
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)

**To Reproduce**
Steps to reproduce the behavior. Example:
1. Install neolink prebuilt binary on ubuntu server 20.04.1
2. Launch neolink
3. Probe media with ffprobe rtsp://127.0.0.1:8554/stream

**Expected behavior**
Neolink reports error 503:

[rtsp @ 0x560e0b82af00] method DESCRIBE failed: 503 Service Unavailable
rtsp://127.0.0.1:8554/lager: Server returned 5XX Server Error reply

**Versions**
NVR software: ffprobe 4.2.4-1ubuntu0.1
Neolink software:055d731feca7362e02d227199c43aa00f8526638 release
neolink 0.3.0
Reolink camera model and firmware: RLC-520, IPC_51516M5M, v3.0.0.136_20121112

**Comment by QuantumEntangledAndy** [comment]
It would be really helpful if you could provide the debug logs of neolink


```bash
RUST_LOG=debug GST_DBG=3 ./neolink --config path/to/conf
```

**Comment by QuantumEntangledAndy** [comment]
P.s. please wrap logs inside triple backticks so that it formats correctly as described [here](https://guides.github.com/features/mastering-markdown/).

For really long logs you could wrap it into a spoiler block

````html
<details>
        <summary>Log</summary>

```
Your log here
```


</details>
````

**Comment by richardklingler** [comment]
Attached the log file...too big to paste here (o;

Actually I can't find anything useful in it....

[neolink.log](https://github.com/thirtythreeforty/neolink/files/5744239/neolink.log)

**Comment by QuantumEntangledAndy** [comment]
Ah this is missing the gstreamer debug sorry my fault. It should be `GST_DEBUG` not `GST_DBG` if you could please try again I'd appreciate it.

```bash
RUST_LOG=debug GST_DEBUG=3 ./neolink --config path/to/conf
```

**Comment by richardklingler** [comment]
Hello

Here the new log:

[neolink.log](https://github.com/thirtythreeforty/neolink/files/5744272/neolink.log)

thanks in advance
richard

**Comment by QuantumEntangledAndy** [comment]
Ah and here is our error `no element "h264parse"` It suggests you have not installed all of the dependencies

**Comment by QuantumEntangledAndy** [comment]
I think you need these:

```bash
sudo apt install \
  libgstrtspserver-1.0-0 \
  libgstreamer1.0-0 \
  libgstreamer-plugins-bad1.0-0 \
  gstreamer1.0-plugins-good \
  gstreamer1.0-plugins-bad
```

**Comment by richardklingler** [comment]
Excellent...that was it (o;

[rtsp @ 0x561c06c65f00] DTS discontinuity in stream 0: packet 9 with DTS 31377, packet 10 with DTS 39034
Input #0, rtsp, from 'rtsp://127.0.0.1:8554/lager':
  Metadata:
    title           : Session streamed with GStreamer
    comment         : rtsp-server
  Duration: N/A, start: 0.099178, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1440, 90k tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_s16be, 16000 Hz, 2 channels, s16, 512 kb/s

**Comment by danielkucera** [comment]
@thirtythreeforty can you please make this solution part of the readme?

**Comment by keionvergara** [comment]
Hey im getting the exact same errors on windows! how do I install these dependencies on windows

**Comment by QuantumEntangledAndy** [comment]
@keionvergara Install gstreamer using the msi from the gstreamer website and make sure you select "complete" install during the installation. Also make sure you set up the environmental variable as indicated i the README
