### ISSUE TITLE
I try to use the docker in the ubuntu without sucess

### ISSUE THREAD

**Issue by nunokaneco** [thirtythreeforty/neolink#127]
Hello Team

I just try to use the docker as mentioned in the readme without success,  I also try to execute the commands after download the current version and unzip also created the myconfig file,  but I can't execute  the command   neolink --config my_config.toml

Can anyone please help me in order to get this to work ?

Thank you and best regards

**Comment by QuantumEntangledAndy** [comment]
This is not a **bug**. But I take it you are not familiar with terminals and exceutables.

1. Download the latest version
2. Unzip it
3. Copy the file to the folder `/usr/local/bin/`
```bash
cd the_location_you_unzipped_to
sudo cp neolink /usr/local/bin/neolink
```
4. Make it executable
```bash
sudo chmod +x /usr/local/bin/neolink
```
5. Check neolink runs
```bash
neolink --help
```
6. Make and save a my_config.toml with the right settings
7. Run neolink with the config
```bash
neolink --config my_config.toml
```

Send logs or pictures of anything you have trouble with.

Read the other issues people have had: https://github.com/thirtythreeforty/neolink/discussions/126.

Read the documentations: https://github.com/thirtythreeforty/neolink/tree/master/docs

**Comment by nunokaneco** [comment]
> This is not a **bug**. But I take it you are not familiar with terminals and exceutables.
> 
> 1. Download the latest version
> 2. Unzip it
> 3. Copy the file to the folder `/usr/local/bin/`
> 
> ```shell
> cd the_location_you_unzipped_to
> sudo cp neolink /usr/local/bin/neolink
> ```
> 
> 1. Make it executable
> 
> ```shell
> sudo chmod +x /usr/local/bin/neolink
> ```
> 
> 1. Check neolink runs
> 
> ```shell
> neolink --help
> ```
> 
> 1. Make and save a my_config.toml with the right settings
> 2. Run neolink with the config
> 
> ```shell
> neolink --config my_config.toml
> ```
> 
> Send logs or pictures of anything you have trouble with.
> 
> Read the other issues people have had: #126.
> 
> Read the documentations: https://github.com/thirtythreeforty/neolink/tree/master/docs

Thank you for your reply, now it's working again more our less.... I just have success executing the neolink but now I'm facing this issue  

```
./neolink --config my_config.toml
[2021-01-25T11:45:20Z INFO  neolink] Neolink 055d731feca7362e02d227199c43aa00f8526638 release
[2021-01-25T11:45:20Z WARN  neolink] The format config option of the camera has been removed in favour of auto detection.
[2021-01-25T11:45:20Z INFO  neolink] driveway: Connecting to camera at 192.168.2.168:9000
[2021-01-25T11:45:20Z INFO  neolink] driveway: Connecting to camera at 192.168.2.168:9000
[2021-01-25T11:45:20Z INFO  neolink] driveway: Connected and logged in
[2021-01-25T11:45:20Z INFO  neolink] driveway: Starting video stream subStream
[2021-01-25T11:45:20Z INFO  neolink] driveway: Connected and logged in
[2021-01-25T11:45:20Z INFO  neolink] driveway: Camera time is already set: 2021-01-25 11:45:20 +0
[2021-01-25T11:45:20Z INFO  neolink] driveway: Camera reports firmware version v3.0.0.42_20062900
[2021-01-25T11:45:20Z INFO  neolink] driveway: Starting video stream mainStream
[2021-01-25T11:46:59Z WARN  neolink::bc_protocol::media_packet] Possibly truncated packet or unknown magic in stream
[2021-01-25T11:47:00Z WARN  neolink::bc_protocol::media_packet] Possibly truncated packet or unknown magic in stream

```

Can you please help me understanding what is this error ?

Thank you and best regards

**Comment by QuantumEntangledAndy** [comment]
Everything seems to be working have you tried to connect with an rtsp client like ffplay or VLC?

You have a warning about a new magic code. This should not stop the stream from working it just means your camera is sending a data type we haven't seen before. Could you tell us what your camera model is? If you know how to. Use wireshark you could send us the data packets of your new camera and we can study what it means. But a wireshark dump is a technical subject and may be too difficult for you.

**Comment by nunokaneco** [comment]
> Everything seems to be working have you tried to connect with an rtsp client like ffplay or VLC?

This WARN appears when I try to access the stream over HA Home Assistant, from the VLC is working well without any issue, The Camera model is the REOLINK E1, regrading the wireshark I will try and share 

Thank you and best regards

**Comment by QuantumEntangledAndy** [comment]
The WARN is coming from the camera side of the connection not the HA end so they should not be related.

I use HA at home too, make sure you set HA to use TCP and not UDP when connecting to neolink.

This is my ha config

```yml
# Cameras
camera:
  - platform: ffmpeg
    name: Live CAMNAME
    input: -rtsp_transport tcp -probesize 500 -i rtsp://127.0.0.1:8554/CAMNAME/subStream
```

**Comment by QuantumEntangledAndy** [comment]
Don't worry about the wireshark as I have an E1 with dumps already I think in this case it is just a truncated packet from the stream trying to start mid packet

**Comment by thirtythreeforty** [comment]
Hey guys glad you got this working - I'm going to convert to a discussion. Feel free to keep talking
