### ISSUE TITLE
Docker Buffer Error

### ISSUE THREAD

**Issue by RedTapeTV** [thirtythreeforty/neolink#132]
I am using the docker image and after a couple of hours of being on for no issues, I am now getting the following error. Any ideas?

(neolink:6): GStreamer-CRITICAL **: 08:03:30.469: gst_mini_object_lock: assertion 'GST_MINI_OBJECT_IS_LOCKABLE (object)' failed

(neolink:7): GStreamer-CRITICAL **: 08:05:51.333: gst_buffer_n_memory: assertion 'GST_IS_BUFFER (buffer)' failed

Here is my config file.

 bind = "0.0.0.0"
 
 [[cameras]]
 name = "Driveway"
 username = "admin"
 password = "password"
 address = "192.168.1.71:9000"
 stream = "mainStream"

**Comment by QuantumEntangledAndy** [comment]
Did you resolve this? Docker and gstreamer do not play well with each other with a few known errors (mostly segfaults) it may be related to that. Could you replicate the issue without docker?
