### ISSUE TITLE
Issue setting up second camera

### ISSUE THREAD

**Issue by trancertong** [thirtythreeforty/neolink#139]
**Describe the bug**
When setting up two Reolink Lumus cameras, only one stream works. The other gives the following error repeatedly:
```
[2021-03-04T05:48:04Z INFO neolink] Rio02: Connecting to camera at 192.168.1.222:9000
[2021-03-04T05:48:04Z INFO neolink] Rio02: Connected and logged in
[2021-03-04T05:48:04Z INFO neolink] Rio02: Camera time is already set: 2021-03-03 19:48:03 -10
[2021-03-04T05:48:04Z INFO neolink] Rio02: Camera reports firmware version v2.0.0.669_20060200
[2021-03-04T05:48:04Z INFO neolink] Rio02: Starting video stream subStream
[2021-03-04T05:48:09Z ERROR neolink::bc_protocol::connection] Deserialization error: DeserializationError(IoError(Custom { kind: UnexpectedEof, error: "Read returned 0 bytes" }))
[2021-03-04T05:48:09Z ERROR neolink] Error streaming from camera Rio02, will retry in 1s: Timeout
```
If I change the configuration for this camera (192.168.1.222) to use channel_id=0 it works correctly but then my other camera does not work. It seems whatever camera is defined as channel_id=1 the config file does not work. I'm running the program in a Docker container on Unraid, but also set up a Windows PC to run Neolink and the same error occurred.

My config file:
```
bind = "0.0.0.0"

[[cameras]]
name = "Rio01"
username = "<username>"
password = <password>
address = "192.168.1.221:9000"
stream = "subStream"
channel_id = 0

[[cameras]]
name = "Rio02"
username = "<username>"
password = <password>
address = "192.168.1.222:9000"
stream = "subStream"
channel_id = 1
```

**To Reproduce**
1. Configure Neolink to use two cameras (Reolink Lumus)

**Expected behavior**
Both cameras should be able to stream simultaneously. If I switch the camera's order in the configuration, each camera will work as long as they are the first configured in the config file.

**Versions**
NVR software: Zoneminder 
Neolink software: Neolink 0.3.0 (unknown commit) release
Reolink camera model and firmware: 2x Reolink Lumus, firmware version 2.0.0.669_20060200

**Comment by QuantumEntangledAndy** [comment]
The channel_id should be zero in both cases. The channel_id is only for the NVM when there are more than 1 camera on a single ip address.

**Comment by trancertong** [comment]
Aha, that works, I feel silly, thank you!

Great work on this, I really appreciate it and you taking the time to help me.

**Comment by QuantumEntangledAndy** [comment]
No worries glad it is useful for you

**Comment by QuantumEntangledAndy** [comment]
I think we can close this issue right?

**Comment by trancertong** [comment]
Yes, it's been working perfectly, thank you.
Sorry if there was something I was supposed to do, I've never used GitHub
before.
-dKL

**Comment by QuantumEntangledAndy** [comment]
I see well just press the close issue button
