### ISSUE TITLE
Timeout loop after update/reboot/disconnect/crash

### ISSUE THREAD

**Issue by hh1209** [thirtythreeforty/neolink#14]
When a camera is suddenly disconnected from the network by unplugging a cable, or Neolink crashes or is killed, sometimes the disconnected camera(s) will no longer stream with Neolink's stock timeout threshold once the camera is reconnected. Neolink will try to connect, will successfully reconnect, then will immediately time out, then reconnect again successfully, then time out again, and repeat the cycle indefinitely. This disconnect/timeout problem only happens sometimes, and very rarely. Most of the time, I can pull the plug on any of the cameras, reconnect, and everything works fine.

I can manually set the timeout threshold to the timeout-ing camera to 5 seconds in the Neolink config file, then it streams perfectly.

I also noticed that (on the rare occasion) after the camera is disconnected and begins to time out, the time and date overlay will disappear from the top of the feed. The date is reset to the year 2000 in the settings, and it won't display it on the feed until I sync the clock with the computer using the Reolink app.

Once I sync the system time with the camera, the date/time overlay will return to the top of the feed, and I can turn the timeout back down to one second in the Neolink config file for that camera and it streams perfectly, without any timeouts.

I'm not sure what's causing the camera's date and time settings to be destroyed, but I think that is what is causing the timeout issue. A workaround for this might be to figure out how the time is set on the camera via the Baichuan protocol, then have Neolink sync the system time with the camera on every successful reconnect.

**Comment by thirtythreeforty** [comment]
Hm that's *a* problem, but not *Neolink*'s problem. Hah. So, does the 5 second threshold work with cameras that have lost their date/time?

I'm happy to have a longer timeout if the camera needs it. I'm also happy to push the date/time, which sounds like it would be more useful anyway.

**Comment by hh1209** [comment]
> So, does the 5 second threshold work with cameras that have lost their date/time?

Yes, the 5 second timeout with cameras that have lost date/time allows flawless stream.

I think syncing the time would be a useful feature as well; in the event of a power loss (and backup supply runs out) the cameras' times/date settings all are lost, so it would be nice if neolink could set this automatically. I'm pretty sure it would also fix this camera bug.

**Comment by thirtythreeforty** [comment]
Sounds like a plan. Can you take a pcap of the official client setting the time? Or better yet, of the official client recovering this scenario?

**Comment by thirtythreeforty** [comment]
You can send me the pcaps privately, since they basically have plaintext passwords.

**Comment by hh1209** [comment]
Sure thing I'll get them to you tonight

**Comment by hh1209** [comment]
Don't know why I just realized this, but this mostly happens when the cameras lose power from being unplugged (duh). But it also happens sometimes when Neolink crashes and the cameras still have power.

**Comment by thirtythreeforty** [comment]
Here's a synopsis of this issue: sometimes the cameras lose their clock when rebooting. It is unknown why this happens. This causes a slow video stream startup, and Neolink aggressively disconnects.

There are two workarounds for this:

- Set the timeout to 5s per-camera via the undocumented `timeout` parameter in the config:
```
[[cameras]]
# ...
timeout = { secs = 5, nanos = 0 }
```
- Reset the clock using the Reolink app.

Soon, Neolink will handle this. With all my free time, ha.

**Comment by akennerly** [comment]
I'll add on that this occurs with the D800 as well.  The same OSD issue and lost time occured to me and it was fixed with the undocumented timeout config.
