### ISSUE TITLE
Reolink/Neolink issue connecting more than 2 cams & Cannot stream main&sub D800 to BI at the same time

### ISSUE THREAD

**Issue by ccasecams** [thirtythreeforty/neolink#144]
Hey hey! 

I am having some issues getting more than 2 cameras working with neolink and adding them to BI. 

Equipment used:

Win 10 box
5 x Reolink D800
1 x Reolink RLC-410
Reolink RLN8-410-E NVR
Blue Iris 5
Neolink 0.3.0

I have two issues I am currently hitting that I can't figure out. Just wondering if anyone could lend a helping hand!

Issue 1.) 

When connecting more than 2x D800 camera's to Neolink, I am getting the following error:

 [2021-03-20T01:39:30Z ERROR neolink::bc_protocol::connection] Deserialization error: DeserializationError(IoError(Os { code: 10060, kind: TimedOut, message: "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." }))
[2021-03-20T01:39:30Z ERROR neolink] Error streaming from camera Back_Porch, will retry in 1s: Timeout

I am able to get any 2 camera's working, but not all 5 of my D800's at once. 

Issue 2.)

I am able to get my D800's working in VLC, but I cannot connect them to BI. Everything seems good for the settings I have, and it does work in VLC (Which tells me Neolink is working fine). Here are the settings I am trying:

[[cameras]]
name = "alley"
username = "admin"
password = "NVR Pass"
address = "10.0.0.21:9000"
channel_id = 4

BI settings:

![image](https://user-images.githubusercontent.com/80994929/111856086-c39f4d80-88fe-11eb-9e66-0d1fd1525878.png)

I can get it to work using RTSP in BI, but that seems to be limited to subStream only. 

EDIT
I just read an open Bug (138) that suggested to try and change the BI RTSP port to 8554, and that has at least got me to a '503 Service Unavailable' When configuring mainStream and subStream. 
https://github.com/thirtythreeforty/neolink/issues/138

I am able to configure just mainStream without an issue though. Seems my issue is configuring both subStream and mainStream at the same time. 

Any help is appreciated!

**Comment by QuantumEntangledAndy** [comment]
Yeah the port is definitely 8554.

Can you get main and subStream to work if there's just one camera? Some camera models are limited to only one stream at a time and I want to see if this is the case for yours. There's an open issue about it somewhere that lists which models are affected but I can't seem to find it right now.

If you can connect both then, it may be a bandwidth issue instead since your sending lots of high resolution streams all the time. I think D800s are 4k right? A quick Google sussgests 4k is 20Mbps+ although I don't have a D800 to confirm.

**Comment by twistedddx** [comment]
My rln8-410 can not take many logins either.
It flakes out around 4 connections.

Neolink and official reolink do not connect to these cameras exactly the same.
The official client logs in once and then opens the 8 streams.
The official client also does not stream the main and sub stream at the same time, you pick one at a time.
Neolink logs in once per camera and by default streams both main and sub streams.
Basically the NVR does not have the horse power needed to keep all those logins with all those streams going.

In your neolink config file you should force only the main or sub stream per camera.
See if your NVR can cope with that.

Neolink connecting to an NVR is a bit of an odd use case.
I did the pull request to allow supporting nvr for users that wanted to play with neolink before fully committing to it.
In most cases for neolink you likely would replace the reolink NVR and neolink would direct connect to the cameras.

**Comment by ccasecams** [comment]
Hey hey!

Thanks for the responses and the contributions to this project! 

Issue 1.)
Quantum - Correct, the D800's are 4k. It is a bit of an odd case though, probably NVR related (although it still doesn't make sense to me). I tested this morning and I can create 4 'cams' and I am able to get both cameras with an HD stream, and the same cameras with an SD stream (One stream per 'cam' in BI), but I have to set them up as separate cams in BI. Rather odd as that would use the same bandwidth and logins that the all-in-one (HD/SD) option would. So it seems the only current way with my NVR (I hope this is NVR related), is to separate the subStream and the mainStream connections out as different cams. Issue two might help me take the jump away from the NVR.

Issue 2.) 
Twisted - In testing what you had suggested, it makes sense and is exactly what I am seeing! I can get 4 different mainStream or subStream connections going, but cannot make more than 4 connections. I might need to check if the D800's can be setup with a different POE and used direct with Neolink and BI. D800's were pretty limited "NVR exclusive" cameras. I think I just need to do a little googling and see what other people have setup. 

I am going to close this out as I think I found a decent POE switch (and the BI PC) that should work as a good replacement for the NVR. If all else fails, I can use this POE switch to power my next set of onvif cameras :) 

Many thanks!

**Comment by twistedddx** [comment]
The Reolink NVR exclusive bit is that the cameras do not have a web interface or RTSP function.
The cameras can not work with any common 3rd party NVR solution directly.
That limitation is why Neolink exists to allow those cameras to work with other software.

Those cameras can only talk BC protocol which is what the official Reolink clients and Neolink talk ;)

If you connect the cameras direct to a POE switch external to the NVR, Neolink should be able to talk to the cameras directly fine.
The Reolink NVR can can also still connect to the cameras, but pay attention that the camera would then have the Reolink NVR connected plus Neolink and the camera may have limits to how many clients it can be sending streams to.


It is easy to forget that BI is not connected to the NVR or cameras.
BI connects to Neolink while Neolink connects to the NVR/cameras.
Even if BI only has the main stream connected, by default Neolink would still have both main and sub streams connected and streaming from the hardware.
Neolinks connection to the NVR/cameras is unrelated to how BI is connecting to Neolink.

**Comment by ccasecams** [comment]
Awesome! I think the plan is to let the Reolink NVR beside the POE switch, ready to be hooked back up (FW updates and such) but to keep it disconnected while I have the whole system up and running in BI. This way I get rid of the overhead connections that reolink has to each camera. I could try to run both simultaneously, but it seems like that is probably not necessary. 

Looking forward to getting this up and running! Thanks for the help and tips!
