### ISSUE TITLE
manual install on Raspberry Pi 4

### ISSUE THREAD

**Issue by gogreenpower** [thirtythreeforty/neolink#147]
**Describe the bug**
when I launch the program from the shell I get 

`-bash: neolink: command not found
`

**To Reproduce**
1. Create this configuration file: config.toml
2. Launch Neolink: neolink --config config.toml

**Expected behavior**
neolink to start

**Versions**
gstreamer1.0 installed 
NVR software: Motioneye (haven't got that far yet)
Neolink software: https://nightly.link/thirtythreeforty/neolink/workflows/build/master/release-armhf-buster.zip
Reolink camera model and firmware: Lumus

![neolink start error](https://user-images.githubusercontent.com/9656919/112935520-8173d880-9156-11eb-889c-815ebf7b7ec0.png)
![neolink start error 2](https://user-images.githubusercontent.com/9656919/112936560-9ea9a680-9158-11eb-84ed-a2a151ca2ccb.png)

edit: images

**Comment by gogreenpower** [comment]
probably something I have missed but I cant figure it out

**Comment by QuantumEntangledAndy** [comment]
I take it you are new to linux and command lines. Your first message

- Not found
    Is because you forgot the `./`

Your second error

- Permission denied
    Is because you have not set the executable permission on the file

Run this

```bash
chmod +x neolink
```

That will set the exec permission bit

Then you can use it with

```bash
./neolink --config your_config_file
```

I recommend you read the documentation in `doc/unix_setup.md` in this repo

**Comment by QuantumEntangledAndy** [comment]
p.s. don't use sudo for `neolink` it is not neccecary

**Comment by QuantumEntangledAndy** [comment]
If your goal is to have neolink always run in the background for your NVR I recommend once you have it working you read the docs at `docs/unix_service.md` to learn how to make a background service for neolink

**Comment by gogreenpower** [comment]
executable permission, that was it thanks. Pretty new to command line, most guides do mention chmod -x, might be worth adding to the readme.
