### ISSUE TITLE
More detailed installation instructions

### ISSUE THREAD

**Issue by doneldanderson** [thirtythreeforty/neolink#15]
Trying to get Neolink up and running on a windows 10 computer so I can stream from my B800s right into Blue Iris. I am not a developer and I am lost trying to add paths after installing Gstreamer. Could we get a few more details on install instructions?

**Comment by thirtythreeforty** [comment]
Sorry about that, the first pass was very hastily written. I just added a more detailed guide based on a comment in #11. Can you read the new readme and see if that's more illuminating?

**Comment by thirtythreeforty** [comment]
Gonna close since you indicate in #11 that the new instructions helped. Again feel free to reopen if you have other questions.
