### ISSUE TITLE
Have created a docker image for app

### ISSUE THREAD

**Issue by thadius83** [thirtythreeforty/neolink#16]
Pretty Basic based off the ubuntu base image (rather than source - optimised version will be coming soon built from source and latest code)

docker run  --rm -p 9554:8554  -v <location of your>/neolink.conf:/etc/neolink.conf mr2jzgte/neolink

exposed on port 9554, modify as required.

if needed, troubleshoot via 

docker run  --rm -it -p 9554:8554 --entrypoint bash -v <location of your>/neolink.conf:/etc/neolink.conf mr2jzgte/neolink

Have a builtin watchdog, that if the process isn't running, it will restart it. (may need tweaking)
My first docker image build - so it's a learning curve

**Comment by thirtythreeforty** [comment]
Nice, thanks! Protip, not sure if you know already: when you're doing a source build, [you can use `FROM`](https://docs.docker.com/develop/develop-images/multistage-build/) to copy files out of a previous image (so that you don't get all the Rust toolchain or all the build intermediates baked into the final image).

**Comment by thirtythreeforty** [comment]
If your Dockerfile is open source and automatically built, I'll link to it in Neolink. Or, if you want to help me adapt it, I'm happy to maintain it myself once you get it working.

**Comment by thadius83** [comment]
Yup can send you the Dockerfile in the morning

It’s based just from the standard Ubuntu image + apt install of gstreamer + req, then just a few scripts. 

All open source.

**Comment by thadius83** [comment]
https://github.com/thadius83/docker-neolink/

Only requirement is the source files, and the pre-built to be in the build directory

Working on an alpine image to reduce the size. It's the dependencies of gstreamer that cause the bloat, I suspect I could remove a lot of them manually, but lack of time.

**Comment by thirtythreeforty** [comment]
Cool. If they're true dependencies, you can't remove them. That's what "dependency" means. But if they're recommendations, you can avoid installing them with `--no-install-recommends`.

**Comment by Riza-Aslan** [comment]
@thadius83 woult you update your image with the latest Neolink files? It looks like my E1 should be supported now and i would really love to try it with your docker image.

**Comment by thirtythreeforty** [comment]
@Riza-Aslan give the new official image a shot

**Comment by Riza-Aslan** [comment]
Tried the official image but it didn't work for me. Do I have to start it the same way like the unofficial image or is it different? There are no Information about it on the docker page.

```
root@Synology:~# docker run -p 9554:8554 -v /volume4/docker/Neolink/neolink.conf:/etc/neolink.conf thirtythreeforty/neolink
[2020-07-06T07:56:04Z INFO  neolink] Neolink 0.3.0 (unknown commit) release
Error: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

**Comment by thirtythreeforty** [comment]
You have a small typo: `neolink.conf` should be `neolink.toml`. Looks like
it's working otherwise. That indecipherable error is from Neolink. Todo:
improve :)

>

**Comment by thirtythreeforty** [comment]
I may have goofed up the config filename when I redid it, sorry if so.

**Comment by Riza-Aslan** [comment]
It's starting fine now, but I cannot connect to the stream. I've build an image based on ubuntu with thadius83's dockerfile earlier and this was working for my E1 cams, but i've got wifi issues because of this. See my comment here #27

**Comment by gramilla** [comment]
With docker image get this error
[2020-07-07T08:18:44Z INFO  neolink] Neolink 0.3.0 (unknown commit) release
Error: IoError(Os { code: 21, kind: Other, message: "Is a directory" })
How can i fix it?

**Comment by Riza-Aslan** [comment]
I think you have tried to link your configuration file to a folder. You have to start the container like this:

`docker run -p 9554:8554 -v /folder/neolink.conf:/etc/neolink.conf thirtythreeforty/neolink`

**Comment by thirtythreeforty** [comment]
Here's the sample launch command from the readme. Again, the config file ends in `toml` not `conf`:

```
docker run \
  --restart=on-failure \
  --volume=$PWD/config.toml:/etc/neolink.toml \
  thirtythreeforty/neolink
```

**Comment by Riza-Aslan** [comment]
Sorry...forgot to change it to `toml` before posting.

The official image is still not working for me. It's starting like it should and I can see in the logs that the stream has been startet, but I cannot connect to the stream from VLC or my Synology Surveillance Station. It worked with my own image with neolink version 0.2.0 but not yet with the official one. I've exposed 8554 and both clients take very long before telling me that they couldn't connect. If I try it on a closed port the error comes pretty fast. Do you have any ideas?

**Comment by thirtythreeforty** [comment]
@Riza-Aslan #33 fixed the obviously broken Docker image. Try again. Thanks @m1k1o .
