### ISSUE TITLE
Substream proxying ?

### ISSUE THREAD

**Issue by thadius83** [thirtythreeforty/neolink#18]
Is it possible to pull the substream from camera into neolink rather than just the 4k stream ?

Reason behind this is for a few reasons.
1. I record 24x7, I'd like to optimise the storage by recording a 24x7 low/medium stream, and then on motion detection, switch to recording the HD stream.

2. Processing 4k video streams for real time object detection is painful

Nice to have: Some method of setting the substream output size stream would be useful, unsure if gstreamer can do this natively, or would require ffmpeg

**Comment by thirtythreeforty** [comment]
Yes, this should be possible. If you're compiling, you could try changing the `stream_type` it requests (probably to `"subStream"`), just to see if works:

https://github.com/thirtythreeforty/neolink/blob/283f70cac494051e8bf586f327e2ac8399a2cde0/src/bc_protocol.rs#L252-L268

**Comment by thirtythreeforty** [comment]
You'd ask the camera to set the substream size, since Neolink just forwards the stream. Right now you can do this in the official Reolink client.

**Comment by thirtythreeforty** [comment]
I tried this, and it seems the substream doesn't Just Work. Possibly it's H.264 or some other departure from the fairly inflexible defaults Neolink is expecting.
