### ISSUE TITLE
"Balanced" stream

### ISSUE THREAD

**Issue by jkutia** [thirtythreeforty/neolink#189]
Hi there, is it possible to also stream the "balanced" compression? (896 x 512 on the B800).
The mainStream is 4k and the subStream is 640x352 so the balanced resolution may provide a better middle ground for running Frigate 

Thanks!

**Comment by QuantumEntangledAndy** [comment]
Possible, certainly, capable right now, no.

It's just not something I've seen on my camera so I just don't know how the client should request such a stream.

Do you know how to do a wireshark packet capture? If so I can read the packets of your camera and learn from that.

**Comment by jkutia** [comment]
Hi Andy, sure I just made a packet capture with filtering by IP (NVR and applicable cam only). At the same time, I cycled between the 3 compression modes in the Reolink Client. Let me know if there are other things to check and I can run it again

Thanks!

https://drive.google.com/file/d/1OU_mrYd9feN11NiSTqyndorED07lJg69/view?usp=sharing

**Comment by QuantumEntangledAndy** [comment]
Cool, would you mind if I added some of these B800 packets into the test suite? I am working on UDP at the moment so it might take me a few days before I can work on this balanced stream thing.

**Comment by jkutia** [comment]
Sure no problem. Just let me know if I can capture anything else later. Cheers

**Comment by QuantumEntangledAndy** [comment]
So looking through this it seems to internally be called externStream


```xml
<?xml version="1.0" encoding="UTF-8" ?>
<body>
<Preview version="1.1">
<channelId>0</channelId>
<handle>1024</handle>
<streamType>externStream</streamType>
</Preview>
</body>
```

I'll what happens if I ask my camera for this type

**Comment by QuantumEntangledAndy** [comment]
So my camera will give me a stream when `externStream` is connected but its the same as the subStream in terms of quality

**Comment by QuantumEntangledAndy** [comment]
If you can build it yourself and test it that would be great. It's on my fork

https://github.com/QuantumEntangledAndy/neolink

Under the branch extern_stream

If not I'll try and build an artifact for download

**Comment by QuantumEntangledAndy** [comment]
If you just want a download the build artifacts are [here](https://github.com/QuantumEntangledAndy/neolink/actions/runs/1132336706) scroll down to where it says this:

<img width="715" alt="Screenshot 2021-08-15 at 16 20 11" src="https://user-images.githubusercontent.com/13386481/129473662-17425524-9a3a-40b6-8aaf-4c32e8a103bc.png">

and download the one for you

**Comment by QuantumEntangledAndy** [comment]
You need to add the following to you camera config

```toml
stream = "all"
```

This will create a stream for main/sub/extern

If you just want to try extern then add this

```toml
stream = "externStream"
```

If you ommit these options you will just get main and sub

**Comment by jkutia** [comment]
That's working great, thanks Andy!

**Comment by QuantumEntangledAndy** [comment]
I can't close the issue since this isn't my repo
