### ISSUE TITLE
Trying to install on Raspberry Pi OS libgstreamer-plugins-good1.0-0 missing

### ISSUE THREAD

**Issue by Morphy99** [thirtythreeforty/neolink#190]
**Describe the bug**
I'm getting this error which is likely due to apt not finding libgstreamer-plugins-good1.0-0

`neolink: error while loading shared libraries: libgstrtspserver-1.0.so.0: cannot open shared object file: No such file or directory`

**To Reproduce**

Trying to install dependencies:

`sudo apt install libgstrtspserver-1.0-0 libgstreamer1.0-0 libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-good1.0-0`

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libgstreamer-plugins-good1.0-0
E: Couldn't find any package by glob 'libgstreamer-plugins-good1.0-0'
E: Couldn't find any package by regex 'libgstreamer-plugins-good1.0-0'
```

**Comment by QuantumEntangledAndy** [comment]
Just omit it. We should really update the docs to not include that one.

**Comment by QuantumEntangledAndy** [comment]
There is no `libgstreamer-plugins-good1.0-0` plugin and this made it into the docs as a copy paste error. The correct packets are just this I believe:

```bash
apt install \
  libgstrtspserver-1.0-0 \
  libgstreamer1.0-0 \
  libgstreamer-plugins-bad1.0-0 \
  gstreamer1.0-plugins-good \
  gstreamer1.0-plugins-bad
```

**Comment by Morphy99** [comment]
> Just omit it. We should really update the docs to not include that one.

Ok I can update the docs if it saves you a job?

Any idea why I'm getting the error on starting neolink then?

`neolink: error while loading shared libraries: libgstrtspserver-1.0.so.0: cannot open shared object file: No such file or directory`

**Comment by QuantumEntangledAndy** [comment]
You can make a PR if you want.

Can you confirm that the `libgstrtspserver-1.0-0` package is installed?

**Comment by Morphy99** [comment]
Yep:
`libgstrtspserver-1.0-0 is already the newest version (1.14.4-1)`

```
dpkg-query -l 'libgstreamer*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                   Version          Architecture Descrip
+++-======================================-================-============-=======
ii  libgstreamer-gl1.0-0:arm64             1.14.4-2+deb10u1 arm64        GStream
ii  libgstreamer-gl1.0-0:armhf             1.14.4-2+deb10u1 armhf        GStream
ii  libgstreamer-opencv1.0-0:arm64         1.14.4-1+deb10u2 arm64        GStream
ii  libgstreamer-plugins-bad1.0-0:arm64    1.14.4-1+deb10u2 arm64        GStream
ii  libgstreamer-plugins-bad1.0-dev:arm64  1.14.4-1+deb10u2 arm64        GStream
ii  libgstreamer-plugins-base1.0-0:arm64   1.14.4-2+deb10u1 arm64        GStream
ii  libgstreamer-plugins-base1.0-0:armhf   1.14.4-2+deb10u1 armhf        GStream
ii  libgstreamer-plugins-base1.0-dev:arm64 1.14.4-2+deb10u1 arm64        GStream
ii  libgstreamer1.0-0:arm64                1.14.4-1         arm64        Core GS
ii  libgstreamer1.0-0:armhf                1.14.4-1         armhf        Core GS
ii  libgstreamer1.0-dev:arm64              1.14.4-1         arm64        GStream
```

**Comment by QuantumEntangledAndy** [comment]
Ah can I also confirm you are using the armhf binary for neolink?

**Comment by QuantumEntangledAndy** [comment]
Also I am not seeing `libgstrtspserver-1.0-0` in your list.  Can you grep `libgst` instead because it named differently

**Comment by Morphy99** [comment]
> Ah can I also confirm you are using the armhf binary for neolink?

I'm pretty sure I am. I will double check as I did this pretty late last night and had a couple of different zips downloaded and transferred with USB as I couldn't use wget for them. Just looking at the [proto-UDP branch](https://github.com/QuantumEntangledAndy/neolink/actions/runs/1132364114) and I can see there is release-arm64-buster which is what I should be using I guess as I'm 64-bit Raspberry Pi OS. I got confused with it not being shown on the main readme.

**Comment by QuantumEntangledAndy** [comment]
You can use the armhf one or the arm64 they should both work

**Comment by QuantumEntangledAndy** [comment]
Just go to this [link](https://github.com/QuantumEntangledAndy/neolink/actions/runs/1134235172) scroll down to this:

<img width="400" alt="Screenshot 2021-08-16 at 15 02 39" src="https://user-images.githubusercontent.com/13386481/129531328-c429fb1d-f633-45f2-b938-fe0b1f85a675.png">

Then try the armhf one and maybe the arm64 too. I think maybe you have the `libgstrtspserver-1.0-0` library for either armhf or arm64 but not both or something.

Maybe try running

```bash
ldd neolink
```

And check that the librariy files it prints out all exist

**Comment by Morphy99** [comment]
I got it, it was the neolink file arm64 that worked. I'll do a PR for the docs later on as I think the installation could be clearer for noobs like me!

**Comment by QuantumEntangledAndy** [comment]
Did you UDP work at all? I am really curious as to it usability on actual camera models

**Comment by Morphy99** [comment]
I'll give it a go! I'm curious too! I'll update you on the other thread.

**Comment by QuantumEntangledAndy** [comment]
Thanks I am eagerly awaiting the bug report/triage/crying about poor code/or maybe just maybe success
