### ISSUE TITLE
SMD SOIC8 socket

### ISSUE THREAD

**Issue by gigawatts** [thirtythreeforty/neolink#20]
From your article, you stated:
`I was wanting to try out a really neat little SOIC socket I had discovered and ordered on Taobao a little while back.`

Can you provide a link to that socket? I've been meaning to install exactly such a socket in a very troublesome laptop with a Winbond SOIC8 BIOS flash chip that loves to corrupt itself every couple years, requiring an extraction and reflash to get working again. I fear the next removal/reinstall cycle might lift some traces.

**Comment by thirtythreeforty** [comment]
Certainly - it's a "Wieson IC socket" - [here on Taobao for $1.50](https://item.taobao.com/item.htm?id=529625834683) and looks like [here on another site for $8.50](http://www.bios-chip24.com/SOIC-8-socket-SMD-Type/en) (but you don't have to deal with Taobao).

**Comment by gigawatts** [comment]
Cool, thank you. Just to confirm this same socket will fit my BIOS chip, what are the package dimensions of your SPI flash chip?

**Comment by thirtythreeforty** [comment]
The 208-mil 8 pin one - I think this is the "ridiculously standard" size.
Winbond's package code SS.

>
