### ISSUE TITLE
Unable to stream from B400

### ISSUE THREAD

**Issue by xyphos10** [thirtythreeforty/neolink#21]
Hello, first of all good work on this project and I am just reaching out because I am unable to get this to work with our B400 cameras. I have attached the debug log file from neolink.

Also, I noticed that if I upgrade the firmware on the B400 to build 20041560 (latest by reolink) the stream fails to start between neolink and the camera. I have also attached this log file.

Camera Firmware: B400 build 18092103 IPC_5128M
VLC: v3.0.11
FFplay: ffplay version git-2020-06-20-29ea4e1
OS: Linux web 5.3.0-59-generic #53~18.04.1-Ubuntu 
Neolink: version 0.2.0 Commit 9a0eb56

[stream.log](https://github.com/thirtythreeforty/neolink/files/4814356/stream.log)

[B400-build20041560.log](https://github.com/thirtythreeforty/neolink/files/4814400/B400-build20041560.log)

**Comment by thirtythreeforty** [comment]
Hey awesome! This is a similar symptom as #19 - I suspect both of these cameras use H.264.

The good news is the cameras use exactly the same protocol:

```
[2020-06-22T16:20:59Z DEBUG neolink::bc_protocol::connection] Ignoring uninteresting message ID 79
```

(This means we are receiving intelligible messages from the camera.)

Would you be willing to send me a saved/exported video from your camera using the official Reolink client? I could validate that it's using H.264 and add support.

**Comment by xyphos10** [comment]
Hello, here is a link to a small video from the camera [B400-Video](https://eceguerrerj.com/uploads/vid.mp4)

**Comment by thirtythreeforty** [comment]
Perfect, thanks

**Comment by thirtythreeforty** [comment]
I am going to consolidate this issue into #19 which I am renaming to "H.264 cameras." Big thanks for the sample video.
