### ISSUE TITLE
bash: /usr/local/bin/neolink: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by timknowlden** [thirtythreeforty/neolink#214]
**Describe the bug**
bash: /usr/local/bin/neolink: cannot execute binary file: Exec format error

**To Reproduce**
Steps to reproduce the behavior. Example:
1. Create this configuration file:
2. neolink rtsp --config=your_config.yaml
3. or
4. neolink rtsp --config my_config.toml

Attempting to run on Raspberry pi 3b+ using terminal within hoobs.

Platform | linux
-- | --
Distro | Raspbian GNU/Linux
Release | 10
Codename | buster
Kernel | 5.4.72-v7+
Arch | armv7l
Hostname | raspberrypi

**Comment by QuantumEntangledAndy** [comment]
In most cases an `Exec format error` means you are not using the right binary. For a raspberry pi please use the armhf binary.

**Comment by timknowlden** [comment]
Debian aarch64 (Raspberry Pi 64-bit) (download)
Debian armhf (Raspberry Pi 32-bit) (download)

I did try both of these.

**Comment by timknowlden** [comment]
Elf file type is DYN (Shared object file)
Entry point 0x49568
There are 10 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x0000000000000230 0x0000000000000230  R      0x8
  INTERP         0x0000000000000270 0x0000000000000270 0x0000000000000270
                 0x000000000000001b 0x000000000000001b  R      0x1
      [Requesting program interpreter: /lib/ld-linux-aarch64.so.1]
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000002a9050 0x00000000002a9050  R E    0x10000
  LOAD           0x00000000002a9d70 0x00000000002b9d70 0x00000000002b9d70
                 0x000000000002e3c0 0x000000000002e6d8  RW     0x10000
  DYNAMIC        0x00000000002d7558 0x00000000002e7558 0x00000000002e7558
                 0x00000000000002b0 0x00000000000002b0  RW     0x8
  NOTE           0x000000000000028c 0x000000000000028c 0x000000000000028c
                 0x0000000000000044 0x0000000000000044  R      0x4
  TLS            0x00000000002a9d70 0x00000000002b9d70 0x00000000002b9d70
                 0x0000000000000000 0x00000000000000d8  R      0x10
  GNU_EH_FRAME   0x00000000002648c0 0x00000000002648c0 0x00000000002648c0
                 0x000000000000a914 0x000000000000a914  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x00000000002a9d70 0x00000000002b9d70 0x00000000002b9d70
                 0x000000000002e290 0x000000000002e290  R      0x1

 Section to Segment mapping:
  Segment Sections...
   00     
   01     .interp 
   02     .interp .note.ABI-tag .note.gnu.build-id .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt .init .plt .text .fini .rodata .eh_frame_hdr .eh_frame .gcc_except_table 
   03     .init_array .fini_array .data.rel.ro .dynamic .got .data .bss 
   04     .dynamic 
   05     .note.ABI-tag .note.gnu.build-id 
   06     .tbss 
   07     .eh_frame_hdr 
   08     
   09     .init_array .fini_array .data.rel.ro .dynamic .got

**Comment by QuantumEntangledAndy** [comment]
Also that is the binary for `/lib/ld-linux-aarch64.so.1` amd64 swap it to armhf one

**Comment by timknowlden** [comment]
So started again...

I think the issue is that I can't install gstreamer


Err:1 http://raspbian.raspberrypi.org/raspbian buster/main armhf libgstreamer-gl1.0-0 armhf 1.14.4-2
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:2 http://raspbian.raspberrypi.org/raspbian buster/main armhf gstreamer1.0-gl armhf 1.14.4-2
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:3 http://raspbian.raspberrypi.org/raspbian buster/main armhf gstreamer1.0-x armhf 1.14.4-2
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:4 http://raspbian.raspberrypi.org/raspbian buster/main armhf libwebpmux3 armhf 0.6.1-2
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:5 http://raspbian.raspberrypi.org/raspbian buster/main armhf libsndfile1 armhf 1.0.28-6
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:6 http://raspbian.raspberrypi.org/raspbian buster/main armhf libfluidsynth1 armhf 1.1.11-1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:7 http://raspbian.raspberrypi.org/raspbian buster/main armhf libgstreamer-plugins-bad1.0-0 armhf 1.14.4-1+b1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err:8 http://raspbian.raspberrypi.org/raspbian buster/main armhf gstreamer1.0-plugins-bad armhf 1.14.4-1+b1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/g/gst-plugins-base1.0/libgstreamer-gl1.0-0_1.14.4-2_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/g/gst-plugins-base1.0/gstreamer1.0-gl_1.14.4-2_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/g/gst-plugins-base1.0/gstreamer1.0-x_1.14.4-2_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/libw/libwebp/libwebpmux3_0.6.1-2_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/libs/libsndfile/libsndfile1_1.0.28-6_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/f/fluidsynth/libfluidsynth1_1.1.11-1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/g/gst-plugins-bad1.0/libgstreamer-plugins-bad1.0-0_1.14.4-1+b1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/g/gst-plugins-bad1.0/gstreamer1.0-plugins-bad_1.14.4-1+b1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by timknowlden** [comment]
I have also tried to run apt-get update but it returns this:

hoobs@raspberrypi:/usr/local/bin $ sudo apt-get update
Get:1 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists... Done                            
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
hoobs@raspberrypi:/usr/local/bin $ apt-secure
bash: apt-secure: command not found

**Comment by QuantumEntangledAndy** [comment]
Oh you have to tell it you accept the changes run `apt update` not `apt-get update` then press yes on the promt

**Comment by timknowlden** [comment]
Yeah just this second sussed that... now going to install gstreamer

**Comment by QuantumEntangledAndy** [comment]
Glad to hear it :). Good luck with ha and things
