### ISSUE TITLE
neolink connecting to camera but no RTSP output

### ISSUE THREAD

**Issue by kylekartan** [thirtythreeforty/neolink#22]
neolink .20
gstreamer-1.0-msvc-x86_64-1.16.2
Windows 10 x64
Reolink B400 v2.0.0.448_19061400

Greetings!
tl;dr version: neolink starts successfully and connects to camera but does not produce any available RTSP output.
---
I haven't been able to figure out how to save the debug output to a file, but once it starts it repeats every 30 seconds:
[date/time: DEBUG neolink::gst] RTSP: Media Configured

(the 30 second delay seems to be the NVR attempting to connect)

I've tried viewing the RTSP stream with VLC, Blue Iris, Milestone, no success. Usually the client tries to connect and says "cannot connect" "no stream available" etc.

Let me know if you need further information.

**Comment by kylekartan** [comment]
Sounds similar to issue #19 
(that'll teach me not to refresh the bug list before submitting)

**Comment by thirtythreeforty** [comment]
Hey! Yep, since it's B400 it's actually #21, but thank you for the report regardless. I have a sample video from the B400 so I think I will be adding more robust support very soon (tm).
