### ISSUE TITLE
Improve compatibility with third party video players

### ISSUE THREAD

**Issue by thirtythreeforty** [thirtythreeforty/neolink#23]
**Describe the bug**
Currently many video players cannot play video coming out of the RTSP server (see trouble users are having in #19 for example).  This is probably because their receive buffers are too small for a 4K keyframe, or else the OS is dropping UDP packets because each keyframe is a lot of traffic all at once.

**To Reproduce**
Open Neolink's RTSP stream from any Reolink camera in VLC.  No video.  In other players, at best it's garbled.

**Expected behavior**
The video should play, without any monkeying with receive buffers, protocols, or other technical details.

Ideas: "smooth out" the incoming key frames that cause so many problems by rate-limiting them just a little bit.

**Comment by twistedddx** [comment]
If the file format you are seeing is the same as the files the official client writes to files it may explain your 3rd party player compatibility also.
You are somewhat depending on luck for the decoder to recognize the h264 video data hidden between other unrecognized data.
Eg the video decoder is having to deal with BC headers and likely also has a bunch of audio data at the end of each frame.

I say BC headers and file format but it is just as likely the format was created by Hisilicon.

I personally found that any VLC higher than 2.2.8 on Windows can not correctly select its raw h264 decoder even if manually set. 
So modern VLC is a poor choice to try to force playback of h264 BC files in their non standard container.
Other FFmpeg based decoders do a better job in that they do not suffer from this bug, eg LAV filters can often play the video portion of the files like you want VLC to do.

FFmpeg's AAC decoder is currently unable to luck auto recognize the audio data within BC format.

**Comment by thirtythreeforty** [comment]
Interesting, thank you for the [link to the file format](https://www.wasteofcash.com/BCConvert/BC_fileformat.txt) in #4. I had run across your tool, but not the text document.

The Gstreamer H.265 frame finder embedded in Neolink successfully recognizes the H.265 stream from the raw `binaryData` stream passed from the cameras. There's no guarantee made that this is actually raw H.265, however, I had just assumed... I will reopen some of my pcaps and see if the contents of binaryData match the header format you describe.

**Comment by thirtythreeforty** [comment]
I'm going to punch something if there's another stateful parser layer...

**Comment by thirtythreeforty** [comment]
This is completely fixed in my testing with VLC. @QuantumEntangledAndy added PTS and DTS timestamps to the stream and it's completely fluid.
