### ISSUE TITLE
Password with ^ and/or ! doesn't work

### ISSUE THREAD

**Issue by vdbrink** [thirtythreeforty/neolink#242]
I had a password with a `^` and a `!` in it which didn't work.

I knew the url was correct because I tested it with VLC media player with this description: https://support.reolink.com/hc/en-us/articles/360007010473-How-to-Live-View-Reolink-Cameras-via-VLC-Media-Player

After I removed these characters from the url and camera password it works. Something with escaping the characters.
I tried with single and double quotes around the rtsp url but that doesn't make any difference.

Version 2.1.1

**Comment by QuantumEntangledAndy** [comment]
Perhaps you could share your setup such as your `neolink.toml` etc.

Also you mentioned a password in the rtsp url. The rtsp is not password protected by default. Please ensure that you have setup the stream for basic auth in the config.

**Comment by QuantumEntangledAndy** [comment]
Did you get this resolved?

**Comment by vdbrink** [comment]
I changed the password (and setup the password in the config).

**Comment by QuantumEntangledAndy** [comment]
Glad to hear it :)
