### ISSUE TITLE
Has anyone tried: Reolink->Neolink->Homebridge->HomeKit ?

### ISSUE THREAD

**Issue by mas0nwest** [thirtythreeforty/neolink#277]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex: "I'm always frustrated when [...]"

**Describe the solution you'd like**

**Comment by QuantumEntangledAndy** [comment]
Not that I'm aware of although if you can get a generic rtsp source in homebridge it should work fine.

**Comment by MichaelCasaDev** [comment]
I'm using this plugin for homebridge ->  https://github.com/Sunoo/homebridge-camera-ffmpeg

**Comment by mas0nwest** [comment]
> I'm using this plugin for homebridge -> https://github.com/Sunoo/homebridge-camera-ffmpeg
Finally tried neolink with homekit and its amazing! I use scrypted for neolink its a lot faster than homebridge
