### ISSUE TITLE
main- and sub-stream streaming prevents use of other clients

### ISSUE THREAD

**Issue by thirtythreeforty** [thirtythreeforty/neolink#29]
@hh1209 noticed that the substream consumes another connection to the camera:

> Are you streaming simultaneously from another device (i.e. an NVR, the mobile app, the PC app)? I noticed that once the substreams were added, I was no longer able to stream the HD feed in two places at once.

Experimentally, the cameras can only have two connections active at once. Is it possible to stream both streams on one connection? If so, are the _connections_ the limit, or are the hardware _encoders_?  If the encoders are the limit, it does not matter how many TCP connections there are.

**Comment by hh1209** [comment]
Some clarification:

While Neolink is running (both mainstream and substream), I can view the two lower-quality streams on the Reolink Android App ("Fluent" and "Balanced" in the app). However, the app immediately says "live viewing failed" when I try to view the 4K stream.

Also, before substreaming functionality was added to Neolink, I had no trouble loading the 4K stream on other clients. Maybe this indicates a software block of some kind?

I can do some more testing on this today and will post results.

**Comment by thirtythreeforty** [comment]
My theory is that there are two hardware encoder units. When something connects, one of them is used for that stream.  When it's out of available encoders, you get errors.

If this is true, it's Reolink's fault that the output of the encoder isn't shared to various clients if possible. If you're only streaming either of `mainStream` or `subStream` to Neolink, is the official app able to display all possible streams?

**Comment by hh1209** [comment]
So I just tried streaming just one 4k feed from the Reolink client. I then tried to connect Neolink (with both streams running) and I get weird video messages. Could be the camera denying the stream?

![Weird video message](https://user-images.githubusercontent.com/54970289/86618681-f70f9700-bf7e-11ea-8387-79c8e3df9e93.PNG)

**Comment by thirtythreeforty** [comment]
Yeah, so you're getting the opposite end of what the client experiences when Neolink is already running. Can you rerun with
```
set RUST_LOG=neolink=debug
```
? It will print that "weird video message."

**Comment by thirtythreeforty** [comment]
Remember, if you exceed two active streams, the third won't work.

**Comment by hh1209** [comment]
Here's the output: 

`[2020-07-06T17:11:49Z INFO  neolink] southwestcorner: Connecting to camera at 192.168.1.10:9000                                                                        [2020-07-06T17:11:49Z DEBUG neolink::bc::xml] Enum: start to parse "body"                                                                                              [2020-07-06T17:11:49Z DEBUG neolink::bc::xml] Struct: start to parse "body"                                                                                            [2020-07-06T17:11:49Z DEBUG neolink::bc::xml] Struct: start to parse "Encryption"                                                                                      [2020-07-06T17:11:49Z DEBUG neolink::bc::xml] Enum: start to parse "body"                                                                                              [2020-07-06T17:11:49Z DEBUG neolink::bc::xml] Struct: start to parse "body"                                                                                            [2020-07-06T17:11:49Z DEBUG neolink::bc::xml] Struct: start to parse "DeviceInfo"                                                                                      [2020-07-06T17:11:49Z DEBUG neolink::bc::xml] Struct: start to parse "resolution"                                                                                      [2020-07-06T17:11:49Z INFO  neolink] southwestcorner: Connected to camera, starting video stream mainStream                                                            [2020-07-06T17:11:49Z WARN  neolink::bc_protocol] Ignoring weird video message                                                                                         [2020-07-06T17:11:49Z DEBUG neolink::bc_protocol] Contents: Bc { meta: BcMeta { msg_id: 3, client_idx: 0, class: 0, encrypted: true }, body: ModernMsg(ModernMsg { xml: None, binary: None }) }                                                                                                                                               [2020-07-06T17:11:50Z DEBUG neolink::bc::xml] Enum: start to parse "body"                                                                                              [2020-07-06T17:11:50Z DEBUG neolink::bc::xml] Struct: start to parse "body"                                                                                            [2020-07-06T17:11:50Z DEBUG neolink::bc::xml] Enum: start to parse "body"                                                                                              [2020-07-06T17:11:50Z DEBUG neolink::bc_protocol::connection] Ignoring uninteresting message ID 33                                                                     [2020-07-06T17:11:50Z DEBUG neolink::bc::xml] Struct: start to parse "body"                                                                                            [2020-07-06T17:11:50Z DEBUG neolink::bc_protocol::connection] Ignoring uninteresting message ID 33                                                                     [2020-07-06T17:11:50Z DEBUG neolink::bc::xml] Enum: start to parse "body"                                                                                              [2020-07-06T17:11:50Z DEBUG neolink::bc::xml] Struct: start to parse "body"                                                                                            [2020-07-06T17:11:50Z DEBUG neolink::bc_protocol::connection] Ignoring uninteresting message ID 33                                                                     [2020-07-06T17:11:50Z DEBUG neolink::bc::xml] Enum: start to parse "body"                                                                                              [2020-07-06T17:11:50Z DEBUG neolink::bc::xml] Struct: start to parse "body"                                                                                            [2020-07-06T17:11:50Z DEBUG neolink::bc_protocol::connection] Ignoring uninteresting message ID 78                                                                     [2020-07-06T17:11:50Z DEBUG neolink::bc::xml] Enum: start to parse "body"                                                                                              [2020-07-06T17:11:50Z DEBUG neolink::bc::xml] Struct: start to parse "body"                                                                                            [2020-07-06T17:11:50Z DEBUG neolink::bc_protocol::connection] Ignoring uninteresting message ID 79                                                                     [2020-07-06T17:11:50Z DEBUG neolink::bc_protocol::connection] Shutting down BcConnection...                                                                            [2020-07-06T17:11:50Z DEBUG neolink::bc_protocol::connection] Shutdown finished OK                                                                                     [2020-07-06T17:11:50Z ERROR neolink] Error streaming from camera southwestcorner, will retry in 1s: Timeout             `

**Comment by thirtythreeforty** [comment]
Oooh,
```
[2020-07-06T17:11:50Z DEBUG neolink::bc_protocol::connection] Ignoring uninteresting message ID 33
```
that's a new message number.

I'll have to add a line that debug prints any uninteresting messages (or indeed all messages).

**Comment by hh1209** [comment]
Sounds good. I'll run again once you do.

**Comment by thirtythreeforty** [comment]
Well, it won't solve the underlying issue. What remains to be seen is if the limit is connections or encoders. I think it's encoders, in which case no amount of changes to Neolink will help - you should just connect your viewers to Neolink, which will correctly share the connection to the camera.

**Comment by hh1209** [comment]
I still can stream the substream in the reolink app though. Even when there are 2 or more connections.

**Comment by thirtythreeforty** [comment]
Hm, interesting. I have no immediate idea why that would be the case then.

**Comment by hh1209** [comment]
This is no longer a problem in Neolink v0.3.0. 

It must be because Neolink uses one less HD in this update?

**Comment by thirtythreeforty** [comment]
Hooray. Yeah, I hosed some things when I merged the substream work (it was requesting a stream named `both` which is bogus). I'd say it's likely related. Glad it's working.
