### ISSUE TITLE
D800 Works fine for few hours, then authentication errors later

### ISSUE THREAD

**Issue by Michaelflat1** [thirtythreeforty/neolink#31]
**Describe the bug**
Seems to work fine, at least it did from 5pm to 11pm

**To Reproduce**
Occurs randomly?
**Expected behavior**
It should continue to work
**Versions**
Latest Reolink firmware on D800. 4K 20fps 4mb/s main stream and 360p 15fps 512kb/s fluent stream.
(gateHQ is substream only of the camera... gateHD is the mainstream.. i seperated like this as i already setup a monitoring display to look at gateHQ.. and didn't want to change RTSP address)

At the end is a pastebin of a *long* log

I think main error is this:
thread 'main' panicked at 'assertion failed: `(left != right)`

https://pastebin.com/5fj380ys

Thanks in advance :)
Running on raspbian raspberry pi, I used cargo to compile it instead of downloading a prebuilt binary. Seems to be the latest version of neolink.

a sudo reboot does not fix this. But I can still login to the camera using the reolink client software, and this seems to fix the issue. Perhaps it is similar to D400 issue where the camera loses time.

**Comment by Michaelflat1** [comment]
It seems the only way to fix this is logging into the windows reolink client. Even asking my grandad to restart the camera (pull out the POE cable and put it in again) does not fix this issue. Seems odd.

**Comment by rygrass** [comment]
Just out of Interest does your Raspberry Pi run via WI-FI? Have you also tried to run it on a different system ( Neolink )?

**Comment by Michaelflat1** [comment]
Pi is connected through gigabit lan, and camera through 100mbps ethernet.. So I'm quite sure they don't disconnect..

I will try running neolink later on my laptop. It just seems odd to work for a while then stop working.

**Comment by Michaelflat1** [comment]
Reolink client for windows also would not login. Camera was reset to factory settings somehow. Perhaps it's a faulty reset button, if it keeps occuring i might have to cut it off.

**Comment by thirtythreeforty** [comment]
Hey thanks for this report. I'm not sure, but it looks like Neolink is mishandling GLib somehow.

But - you said this occurs after hours of runtime. The log only shows a second or so of activity before the `left != right` message. Does anything special happen on the hours-long run prior to the one that you posted? I'd be interested to see that log if you can get it.

**Comment by Michaelflat1** [comment]
> Hey thanks for this report. I'm not sure, but it looks like Neolink is mishandling GLib somehow.
> 
> But - you said this occurs after hours of runtime. The log only shows a second or so of activity before the `left != right` message. Does anything special happen on the hours-long run prior to the one that you posted? I'd be interested to see that log if you can get it.

I ran neolink via ssh remotely off the pi to get the error. I'm not sure how i'd get a log over long term, without physical access to the Pi (setup at grandparents house, 10 miles away). 

The same auth errors were on screen, on the raspberry pi when i came there to investigate the problem. Pi runs headless (no keyboard/mouse) and just uses HDMI to act as an RTSP viewer for the other cameras. (with neolink running at boot [i boot into CLI no GUI here] )

If there is a way to find the log again (i have restarted the pi a few times since then though..) then tell me and i can run ssh commands remotely on it. Just i don't know if there is a way for me to get access to whatever is onscreen. (ssh doesn't have terminal history).

I feel like this is only a one off error now, the camera resetting itself for some reason.

**Comment by Michaelflat1** [comment]
Yep it's done it again. All settings lost on camera. (and also password). 
I have a feeling it might be a hardware fault, hopefully I can return this camera under warranty.. In any case it is quite a big security flaw, leaving the camera exposed with admin and no password.

**Comment by thirtythreeforty** [comment]
Oof yeah, it definitely shouldn't be resetting. I can't imagine that Neolink does anything to make it reset, since it's only sending a command at startup.

**Comment by Michaelflat1** [comment]
Thanks anyway for your help. Pretty amazing bit of work you've got here.
But in future i think i'll get a normal RTSP camera. a 720p medium stream would be very useful for me, and I'd rather not burden the pi in transcoding 4K (!) into 720p. Hikvision IP camera with H265x although more expensive, helps in storage.

**Comment by thirtythreeforty** [comment]
Yep, transcoding would hurt. You can configure the Reolink stuff to output any resolution, although native RTSP will eliminate a bunch of moving parts.  Good luck!
