### ISSUE TITLE
Links to binaries go to 404 as of 12/9/22

### ISSUE THREAD

**Issue by mashmeade** [thirtythreeforty/neolink#328]
Links to binaries seem to be not working, 404s being returned.

**Comment by QuantumEntangledAndy** [comment]
@thirtythreeforty will have to fix the links since he has control of those nightly URLs in the mean time you can check [here](https://github.com/thirtythreeforty/neolink/actions/runs/3616506691)

**Comment by mattlcbesc** [comment]
Is there no way to download the binary until the link is updated?  I checked the link you posted @QuantumEntangledAndy but I don't see how to download from there.

**Comment by QuantumEntangledAndy** [comment]
@mattlcbesc make sure you are logged in, Scroll right to the very bottom of the page and they are under artefacts.

**Comment by mattlcbesc** [comment]
Perfect.  Thanks for that.   Wasn't logged in when I tried.

**Comment by thirtythreeforty** [comment]
Fixed. Sorry for the delay.

The issue was that GitHub changed the default runners, and that changed the artifact names.  Really the artifact names ought to be stable; we'll have to fix that in the CI config.
