### ISSUE TITLE
Update broken binary links in readme

### ISSUE THREAD

**Issue by spacebares** [thirtythreeforty/neolink#329]
Binary links for ubuntu, macos, and windows are broken. They seem to have changed filenames according to:

https://nightly.link/thirtythreeforty/neolink/workflows/build/master

**Comment by QuantumEntangledAndy** [comment]
Duplicate of #328

@thirtythreeforty will have to fix the links since he has control of those nightly URLs in the mean time you can check [here](https://github.com/thirtythreeforty/neolink/actions/runs/3616506691)
