### ISSUE TITLE
Rtsp streams for Argus 3 Pro

### ISSUE THREAD

**Issue by herveaurel** [thirtythreeforty/neolink#344]
Hello, I managed to connect Neolink with my Argus 3 Pro camera, but I don't understand how to have the Flux rtsp.
Should platform generic be created in "camera.yaml"?
Should the rtsp address be written in a card?
Everything I try doesn't work.
And most importantly, the address "rtsp://127.0.0.1:8554/your_camera_name" does not work in a browser.
I do not know what to do.

**Versions**
Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Neolink software: 0.0.3
Reolink camera model and firmware: Argus 3 pro - v 3.0.0.973_22051000

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/64784541/222964829-a0818213-de57-4fb3-bc66-aa7c3729de03.png">

**Comment by QuantumEntangledAndy** [comment]
Not sure what Flux rtsp is. But this is just an issue with integration with ha. Set up a generic camera in ha (we cannot really help with that, ha keeps changing  the method and it's hard to keep up ).

You cannot open the address we give in a browser (browsers don't understand the rtsp protocol). You should test with something like ffplay.


You might want to check out my fork of this project for more recent features and improved support for udp cameras.

**Comment by herveaurel** [comment]
> Not sure what Flux rtsp is. But this is just an issue with integration with ha. Set up a generic camera in ha (we cannot really help with that, ha keeps changing the method and it's hard to keep up ).
> 
> You cannot open the address we give in a browser (browsers don't understand the rtsp protocol). You should test with something like ffplay.
> 
> You might want to check out my fork of this project for more recent features and improved support for udp cameras.

Thank you very much for your answer and excuse my bad English.
So I managed to connect Neolink with my Argus 3 camera. But then I don't know what to do to get the image on my dashboard...

**Comment by herveaurel** [comment]
OK, I just managed to get the picture!!!

**Comment by herveaurel** [comment]
Can you tell me if I can have other services for this camera? (play, pause, ...)
