### ISSUE TITLE
Question: How does neolink affect battery consumption?

### ISSUE THREAD

**Issue by sgargel** [thirtythreeforty/neolink#360]
How does neolink affect battery consumption?

I want to only capture images every 10 minutes. I'm planning to run `neolink` on my raspberry, grabbing image with `ffmpeg` and sending the image to my `S3` bucket.

To save webcam battery, does it make sense to run `reolink` only while caputing the image and stopping it when the image is saved?

**Comment by QuantumEntangledAndy** [comment]
You should perhaps check out the image save command on my fork. That is what it is made for. You can script it quite easily to pull a frame. 

This main fork here is mostly unmaintained. Active development happens mostly in https://github.com/QuantumEntangledAndy/neolink/
