### ISSUE TITLE
Failed to translate camera address - Reolink ARGUS 3 Pro

### ISSUE THREAD

**Issue by RobertSkawinski** [thirtythreeforty/neolink#368]
**Describe the bug**
Caused by:
        Failed to translate camera address
[2023-08-02T17:06:51Z ERROR neolink::rtsp] Error streaming from camera MobileCam2, will retry in 15s: Failed to connect to camera MobileCam2 at Address: 95270005MXFLVSIS on channel 0
    
    Caused by:
        Failed to translate camera addres

**To Reproduce**
1. run current docker image
`thirtythreeforty/neolink`
3. with this config:
```
bind = "0.0.0.0"

[[cameras]]
name = "MobileCam2"
username = "admin"
password = "12341234"
address = "95270005MXFLVSIS"
```

**Expected behavior**
find cam and provide stream

**Versions**
Neolink software: Neolink 0.4.0 
Reolink camera model and firmware: Reolink ARGUS 3 Pro Firmware: v3.0.0.1342_22092001

**Comment by jschaeke** [comment]
I have the same camera and am on the same latest firmware and noticed today it fails to connect too. Could have been broken for a while now but I didn't change anything.
My configuration is using `uid` instead of `address`  of the example above, so I think that might have been a mistake by @RobertSkawinski as it used to work perfectly for me.

```
[2023-08-02T21:32:58Z INFO  neolink_core::bc_protocol::connection::udpconn::discover] Trying remote discovery against reolink servers
[2023-08-02T21:33:04Z ERROR neolink::rtsp] Error streaming from camera reolinkzwembad, will retry in 15s: Failed to connect to camera reolinkzwembad at UID: 95270004ZFTM1VOQ on channel 0
    
    Caused by:
        0: Connection error
        1: Timeout
```

**Comment by QuantumEntangledAndy** [comment]
This fork is mostly unmaintained please see [my fork](https://github.com/QuantumEntangledAndy/neolink) instead for active development. Issues are not addressed on this fork

**Comment by jschaeke** [comment]
Great, works indeed again after using your fork. Thanks for the information and work!

**Comment by RobertSkawinski** [comment]
Hi @jschaeke & @QuantumEntangledAndy 
thanks for your support!

Updating the config address -> uid was the initial solution. Anyway I was not able to get the rtsp stream.

Using your docker image @QuantumEntangledAndy workes perfectly fine! - Thank you!
