### ISSUE TITLE
Changing camera HTTP / port settings.

### ISSUE THREAD

**Issue by ericlathrop** [thirtythreeforty/neolink#383]
**Is your feature request related to a problem? Please describe.**
I flashed a new firmware on my cameras, which disabled the HTTP web site and RTSP streaming. In order to re-enable those, you need to install a windows or mac app, and I do not possess a machine capable of running those apps. The Android app does not possess the required settings checkboxes.

**Describe the solution you'd like**
It would be cool if this app supported a sub command for changing the camera's port settings so I could re-enable the HTTP web site on the camera.

**Comment by QuantumEntangledAndy** [comment]
Please read #370 (or the notice on the top of the readme) then go to the fork mentioned

You will find that there is a new command on that fork called services that does this for http and other ports. The command is very new and not fully out yet so you will need to use the very latest master build. The command is `services` try running `neolink help services` and see if you can make it work.

**Comment by ericlathrop** [comment]
Ah, sorry, somehow I missed that. I'll check it out, thanks
