### ISSUE TITLE
Argus 3 Ultra stays awake

### ISSUE THREAD

**Issue by apocaliss92** [thirtythreeforty/neolink#386]
I could get my Argus 3 ultra, it works pretty well but I can see the camera is always awake and in the log I see a spamming of this message
[2024-09-23T08:12:54Z DEBUG neolink_core::bc_protocol::connection::bcconn] Ignoring uninteresting message id 252 (number: 0)

Not sure if it's happening internally? I do not have any service pointing at it yet

Version is 0.6.2

**Comment by thirtythreeforty** [comment]
Could I redirect you to https://github.com/QuantumEntangledAndy/neolink where this project is now maintained? Thanks for the report!

**Comment by apocaliss92** [comment]
Sorry I was sure to have posted there already :)
