### ISSUE TITLE
Stream audio in same RTSP feed

### ISSUE THREAD

**Issue by thirtythreeforty** [thirtythreeforty/neolink#4]
The cameras optionally support audio - this is disabled by default. However it should be possible to mux this into the same RTSP feed. More reverse engineering is needed to learn the Baichuan format for audio.

**Comment by twistedddx** [comment]
I assume the data coming from the NVR stream is the same data it dumps to files from the client.

If that is the case I have tried to describe my understanding of the file format here:
https://www.wasteofcash.com/BCConvert/BC_fileformat.txt

**Comment by twistedddx** [comment]
I was just testing with an old Swann SWNHD-806CAM and with Reolink NVR and definitely see all the messages in the exact same format coming directly from the camera and NVR.

As a side note Neolink was unable to connect to a SWNHD-806CAM, the dissector complained a lot about:
LUA Error: baichuan.lua:143:  Range is out of bounds

I spotted 1001, 00dcH264, 01dcH264 and 01wb or 05wb(whichever is appropriate for that model IPC) messages from the camera and the NVR. 
All are in what your Wireshark dissector refers to as messageid/type 3 preview video.

MessageID 3 appears to be binary BC file format, as it is a mix of descriptions, video and audio data.

**Comment by QuantumEntangledAndy** [comment]
@thirtythreeforty could you help level up my rust here:

My current implementation of parsing more structure from the video data looks like this

```rust
#[derive(Debug, PartialEq, Eq)]
pub struct VideoIFrame {
    pub magic: Vec<u8>,
    pub video_type: Vec<u8>,
    pub data_size: Vec<u8>,
    pub unknowna: Vec<u8>,
    pub timestamp: Vec<u8>,
    pub unknownb: Vec<u8>,
    pub clocktime: Vec<u8>,
    pub unknownc: Vec<u8>,
    pub video_data: Vec<u8>,
}

impl VideoIFrame {
    pub fn from_binary(binary: &[u8]) -> VideoIFrame {
        VideoIFrame {
            magic: binary[0..4].to_vec(),
            video_type: binary[4..8].to_vec(),
            data_size: binary[8..12].to_vec(),
            unknowna: binary[12..16].to_vec(),
            timestamp: binary[16..20].to_vec(),
            unknownb: binary[20..24].to_vec(),
            clocktime: binary[24..28].to_vec(),
            unknownc: binary[28..32].to_vec(),
            video_data: binary[32..].to_vec(),
        }
    }

    pub fn len(&self) -> usize {
        self.video_data.len() + 32
    }

    pub fn as_slice(&self) -> &[u8] {
        let mut result = self.magic.clone();
        result.extend(&self.video_type);
        result.extend(&self.data_size);
        result.extend(&self.unknowna);
        result.extend(&self.timestamp);
        result.extend(&self.unknownb);
        result.extend(&self.clocktime);
        result.extend(&self.unknownc);
        result.extend(&self.video_data);
        result.as_slice()
    }
}

#[derive(Debug, PartialEq, Eq)]
pub struct VideoPFrame {
    pub magic: Vec<u8>,
    pub video_type: Vec<u8>,
    pub data_size: Vec<u8>,
    pub unknowna: Vec<u8>,
    pub timestamp: Vec<u8>,
    pub unknownb: Vec<u8>,
    pub video_data: Vec<u8>,
}

impl VideoPFrame {
    pub fn from_binary(binary: &[u8]) -> VideoPFrame {
        VideoPFrame {
            magic: binary[0..4].to_vec(),
            video_type: binary[4..8].to_vec(),
            data_size: binary[8..12].to_vec(),
            unknowna: binary[12..16].to_vec(),
            timestamp: binary[16..20].to_vec(),
            unknownb: binary[20..24].to_vec(),
            video_data: binary[24..].to_vec(),
        }
    }

    pub fn len(&self) -> usize {
        self.video_data.len() + 24
    }

    pub fn as_slice(&self) -> &[u8] {
        let mut result = self.magic.clone();
        result.extend(&self.video_type);
        result.extend(&self.data_size);
        result.extend(&self.unknowna);
        result.extend(&self.timestamp);
        result.extend(&self.unknownb);
        result.extend(&self.video_data);
        result.as_slice()
    }
}

#[derive(Debug, PartialEq, Eq)]
pub enum VideoFrame {
    IFrame(VideoIFrame),
    PFrame(VideoPFrame),
}

impl VideoFrame {
    pub fn len(&self) -> usize {
        match self {
            VideoFrame::IFrame(binary) => binary.len(),
            VideoFrame::PFrame(binary) => binary.len(),
        }
    }

    pub fn as_slice(&self) -> &[u8] {
        match self {
            VideoFrame::IFrame(binary) => binary.as_slice(),
            VideoFrame::PFrame(binary) => binary.as_slice(),
        }
    }
}

#[derive(Debug, PartialEq, Eq)]
pub enum BinaryData {
    VideoData(VideoFrame),
    AudioData(Vec<u8>),
    InfoData(Vec<u8>),
    Unknown(Vec<u8>),
}
```

The trouble I am having is with the as_slice (used as part of the serialisation and the passing to gstreamer). I think this function is meant to represent the data a single continuous piece, but when the struct is constructed I break it up. In as_slice I try to reconstruct it as a single piece using extends. But it complains about how I am returning a loacally variable as a borrow

```
returns a value referencing data owned by the current function
```

I am thinking that I could instead write it as something like this:

```rust
pub struct VideoPFrame {
    pub binary Vec<u8>,
}

impl VideoPFrame {
    pub fn from_binary(binary: &[u8]) -> VideoPFrame {
        VideoPFrame {
            binary: binary.to_vec(),
        }
    }
   pub fn magic(&self) -> &[u8] {
      self.binary[0..4]
   }
   pub fn video_type(&self) -> &[u8] {
      self.binary[4..8]
   }
```

Instead but it doesn't feel as elegent. I suppose on the plus side though we could make:

```rust
enum VideoType {
   H264,
   H265,
   Unknown,
}
pub fn video_type(&self) -> VideoType {
      const h264_magic: &[u8] = &[0x48, 0x32, 0x36, 0x34];
      const h265_magic: &[u8] = &[0x48, 0x32, 0x36, 0x35];
      match self.binary[4..8] {
         h264_magic => VideoType::H264,
         h265_magic => VideoType::H265,
         _ => VideoType::Unkown,
      }
   }
```

What do you think would be best?

**Comment by twistedddx** [comment]
Below is the ffmpeg settings I use once the data is split in to true raw data. In particular the adpcm setting is not obvious and not auto detected. I assume a variation of these settings can be used in a streaming context.
The ffmpeg aac and adpcm audio decoders are extremely sensitive to any unexpected data, eg BC headers.

For AAC it may refuse to decode at all if extra data is found. Foobar proved to be reliable in being able to play files with extra junk included.
For ADPCM any extra junk will be assumed to be actual audio and becomes junk audio extending the length of the audio file. Even any padding zeros will be converted to audio.

Convert raw adpcm_ima audio to aac (good for old cameras):
ffmpeg.exe -f g729 -c:a adpcm_ima_oki -i _BC_raw.audio -y _BC_raw.aac

AAC should auto detect if all junk is removed.
Convert raw h264 video + raw aac audio to mp4 file (good for new cameras):
ffmpeg.exe -f h264 -i _BC_raw.video -i _BC_raw.audio -y -c:v copy -c:a copy -map 0:0 -map 1:0 _BC_raw.mp4

**Comment by twistedddx** [comment]
Brush up on your Russian or use Google translate:
https://habr.com/ru/post/422163/

It appears the author in the link has a QCam device which I know is in the BC family.
The author described in 2018 the 00dc/01dc video frames we see.
But he also describes a 03wb with adpcm and gives source to a decoder and how to correctly initialize to get most accurate output based on bytes in the header I could never work out.

PS
There is some back and fourth comments at the bottom which includes how formats like BC media format can come to exist in the CCTV world.

PPS
dc and wb appear to come from avi movi chunk id's.
dc is device independent bitmap compressed.
wb is wave bytes.
The digits before them are supposed to be stream id's.
