### ISSUE TITLE
Installation instructions "Download and extract a prebuilt binary from continuous integration"

### ISSUE THREAD

**Issue by ctrager** [thirtythreeforty/neolink#41]
Sorry, I don't understand what "Download and extract a prebuilt binary from continuous integration".   Am I looking for a single file?  The docker image?

**Comment by ctrager** [comment]
Ah, I see:
docker pull thirtythreeforty/neolink

**Comment by ctrager** [comment]
Part of the problem is I'm new to docker but this is what I've done so far.  I don't know how to get an executable file "neolink".  


```
$ cat my_github_token.txt | sudo docker login https://docker.pkg.github.com -u ctrager --password-stdin
~
~
Login Succeeded

```
Then:
```
$ sudo docker pull docker.pkg.github.com/thirtythreeforty/neolink/neolink:latest

latest: Pulling from thirtythreeforty/neolink/neolink
df20fa9351a1: Already exists 
1345d6395e92: Pull complete 
Digest: sha256:ddec95c2e1b29b9ed3f38137986e7b9a50705e13b5e9540f256118351eac86b1
Status: Downloaded newer image for docker.pkg.github.com/thirtythreeforty/neolink/neolink:latest
docker.pkg.github.com/thirtythreeforty/neolink/neolink:latest

```

Then I look for a file called "neolink" and all I find is this:

`/var/lib/docker/overlay2/805f896659c4af485109bf2402e1891ec24c8cd297f6f0fe031d50b86b7fd601/diff/usr/local/bin/neolink



`

**Comment by thirtythreeforty** [comment]
If you're not already familiar with Docker, I'd recommend downloading the prebuilts from the link in the readme instead. Docker has a learning curve.

**Comment by ctrager** [comment]
The link in the readme goes here:
https://github.com/thirtythreeforty/neolink/actions?query=branch%3Amaster

I didn't know what to do next but then tried clicking on the topmost "master" which goes back to the main page.
https://github.com/thirtythreeforty/neolink

Then I noticed the packages on the right and clicked on it:
https://github.com/thirtythreeforty/neolink/packages/297278

That's when thought, oh, I need docker....

Meanwhile, I'm trying to build and that has led to other errors but that's another story...

**Comment by ctrager** [comment]
Nevermind.  Instead of clicking on the word "master", I needed to click on the text next to the left of it.
