### ISSUE TITLE
Unable to view stream using vlc - "Failed to connect", "Failed to setup RTSP session"

### ISSUE THREAD

**Issue by ctrager** [thirtythreeforty/neolink#42]
Neolink itself seems to be working but I"m unable to view the stream using VLC as a client. This is with a Reolink E1 camera. I can connect to the camera with the reolink app.

Neolink seems to work:
```
./neolink --config my_config.toml
[2020-07-18T19:53:23Z INFO  neolink] Neolink 0.3.0 (unknown commit) release
[2020-07-18T19:53:23Z INFO  neolink] one: Connecting to camera at 10.0.0.21:9000
[2020-07-18T19:53:23Z INFO  neolink] one: Connecting to camera at 10.0.0.21:9000
[2020-07-18T19:53:23Z INFO  neolink] one: Connected to camera, starting video stream mainStream
[2020-07-18T19:53:23Z INFO  neolink] one: Connected to camera, starting video stream subStream

```
My config:
```
bind = "0.0.0.0"

[[cameras]]
name = "one"
username = "admin"
password = "MY PASSWORD"
address = "10.0.0.21:9000"
```

My vlc command line:
`vlc rtsp://127.0.0.1:8554/one 
`
My vlc log:
```
live555 error: Failed to connect with rtsp://127.0.0.1:8554/one
satip error: Failed to setup RTSP session
```
Do I need more vlc command line flags?

**Comment by thirtythreeforty** [comment]
For an E1, you need to let Neolink know it's H.264, because it can't yet autodetect this.

This needs to be clearer in the docs.

Try:

```toml
bind = "0.0.0.0"

[[cameras]]
name = "one"
username = "admin"
password = "MY PASSWORD"
address = "10.0.0.21:9000"
format = "H264"
```

**Comment by ctrager** [comment]
Works!

**Comment by mailq** [comment]
I'd like to reopen this issue.

Same problem with same camera, but different neolink version on docker.

According to the logs - with the workaround from above - I see

`[2023-01-07T22:09:48Z INFO  neolink] Neolink 0.4.0 (unknown commit) release`
`[2023-01-07T22:09:48Z WARN  neolink::rtsp] The format config option of the camera has been removed in favour of auto detection.`

The camera works perfectly via neolink in Home Assistant. So the configuration and neolink for the camera works. But not with VLC.

Firmware version of the camera is v3.0.0.115_20102200

**Comment by QuantumEntangledAndy** [comment]
@mailq Your issue is different then this one. Please open a new issue. If it's working on ha which uses ffmpeg I think but not vlc then the most likely cause of your issue is the vlc udp buffer size not being big enough.

**Comment by hupratt** [comment]
I have the same problem as [ctrager](https://github.com/ctrager) however adding the "format" in the config did not fix it for me.  
The command "vlc rtsp://127.0.0.1:8554/arlon" outputs the following error  "satip stream error: Failed to setup RTSP session". I managed to make it work by using ffplay instead of vlc: "ffplay rtsp://127.0.0.1:8554/arlon"

specs: ubuntu 22.04, vlc version VLC media player 3.0.16 Vetinari (revision 3.0.13-8-g41878ff4f2).

**Comment by QuantumEntangledAndy** [comment]
@hupratt ctranger's issue was that there camera used h264 formatted video and at the time of that issue (3 years ago) we did not automatically detect and swap to the right decoder. Now (for about 2 years now) we do detect and swap the format automatically. So:

1. Format option does nothing as we auto detect now

2. Your issue theresfore cannot be the same and must be for another reason. (New issue please no need to reopen a 3 year old closed issue)

3. You can play in ffprobe and ffplay which means this is to do with the way the rtsp server and client (vlc) are talking with each other. We outsource all rtsp details to gstreamer so perhaps this this the rtsp format not passing vlc standards.

My fork https://github.com/QuantumEntangledAndy/neolink uses updated gstreamer. Please try that one and maybe open a new issue after that.
