### ISSUE TITLE
Check/set time only once per camera, not per stream

### ISSUE THREAD

**Issue by thirtythreeforty** [thirtythreeforty/neolink#57]
This sets the time twice if you have `mainStream` and `subStream` enabled. Not really the end of the world but also not tidy. One of the streams needs to be instructed to be the "management" stream that does all this housekeeping.

_Originally posted by @thirtythreeforty in https://github.com/thirtythreeforty/neolink/pull/54#issuecomment-667162987_

**Comment by twistedddx** [comment]
Once per device, eg per ip, might be better to keep in mind while coding this.
There may be a use case where an Nvr is in use and multiple camera streams are coming from it?
