### ISSUE TITLE
Blue Iris - Error: 8000274d

### ISSUE THREAD

**Issue by Deverall** [thirtythreeforty/neolink#72]
**Is your feature request related to a problem? Please describe.**
I followed the readme in regards to BlueIris and cannot get the camera I am testing to display. I get "Camera: No Signal"
Error: 8000274d

**Describe the solution you'd like**
I just need to know if I did everything correctly? I followed all the instructions, but can't seem to connect to the camera in BlueIris.

![2020-08-26_11-45-50](https://user-images.githubusercontent.com/35110054/91338200-cfc09380-e791-11ea-9551-f32d6f8901b5.png)
![2020-08-26_11-47-16](https://user-images.githubusercontent.com/35110054/91338291-f2eb4300-e791-11ea-943b-b0c72648feba.png)
![2020-08-26_11-48-15](https://user-images.githubusercontent.com/35110054/91338359-0bf3f400-e792-11ea-8aab-c5fb51bd96a9.png)
![2020-08-26_11-49-38](https://user-images.githubusercontent.com/35110054/91338469-3b0a6580-e792-11ea-8cb4-c096837a21fb.png)

Any help would be greatly appreciated!

**Comment by hh1209** [comment]
How long do you wait for BI to start the stream? For me it can take a long time, up to 5ish minutes.

If you keep getting the error after 5-7 minutes, there's definitely an issue
________________________________

**Comment by Deverall** [comment]
I waited overnight. I have given it plenty of time. 

I also tried using the IP directly as well as 127.0.0.1. Clicked inspect to see if it would give any info on connection.

![2020-08-26_11-58-34](https://user-images.githubusercontent.com/35110054/91339276-7bb6ae80-e793-11ea-98fb-53de7e5ec5bc.png)

![2020-08-26_11-59-11](https://user-images.githubusercontent.com/35110054/91339328-90934200-e793-11ea-886d-f2355bc2c7df.png)

**Comment by hh1209** [comment]
In your screenshot the "media/video/rtsp port" is set to 554 instead of 8554. Change that to 8554 and see what she does
________________________________

**Comment by Deverall** [comment]
I changed that and it didn't make any difference.

**Comment by QuantumEntangledAndy** [comment]
I am not familiar with blue iris but I will try my best.

Lets work it out from the start. Can you run neolink and then open a seperate terminal and connect with ffprobe

```bash
ffprobe rtsp://127.0.0.1:8554/front_nw
```

**Comment by QuantumEntangledAndy** [comment]
Also you seem to be connecting as ONVIF which is not correct, as we are not using the ONVIF protocol, just straight rtsp

**Comment by Deverall** [comment]
I only selected the Generic/ONVIF because that is what it shows to use in the BlueIris install screenshots.

**Comment by hh1209** [comment]
@deverall "generic/onvif" is correct. That just tells BI not to use any other camera brands' proprietary protocols

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Deverall** [comment]
![2020-08-31_09-53-28](https://user-images.githubusercontent.com/35110054/91739951-dd01c780-eb6f-11ea-832f-35c12f2ba1ed.png)

**Comment by Deverall** [comment]
I am also testing out BlueIris in a docker container (running via Ubuntu/Wine). You you think that could be causing the issues?

https://hub.docker.com/r/jshridha/blueiris

**Comment by hh1209** [comment]
Yes, that's probably what's wrong. In all my testing running on different windows os's it works with no connectivity issues. Not sure how all the networking binding works out with wine.

Might want to try a different setup, or at least start by doing the ffmpeg test like Andy said.
________________________________

**Comment by Deverall** [comment]
I did do the ffmpeg and pasted the screenshot above.

**Comment by Deverall** [comment]
When I ran the ffprobe via the blueiris container I get the following:

![2020-08-31_10-18-39](https://user-images.githubusercontent.com/35110054/91742409-7a122f80-eb73-11ea-9dcd-016392d45ac6.png)

I seems like its a network issue between the containers? Just not sure how to rectify that as I am pretty new to using containers in general and not a network engineer.

**Comment by QuantumEntangledAndy** [comment]
Could you tell me what the bind address on your toml file? Hopefully it is `0.0.0.0`

You have a docker image running the blue iris?

That image will have its own network.

Could you explain your topology, I think maybe you have something like this

- Host
  - neolink docker
  - bi docker

If thats the case then your bi should point to `host.docker.internal` as the address. And the neolink docker should bind with `-p 8554:8554`

**Comment by QuantumEntangledAndy** [comment]
![image](https://user-images.githubusercontent.com/13386481/91760807-2bf63e00-ebfe-11ea-9ec6-c7f231af4dc4.jpeg)

**Comment by Deverall** [comment]
Yes, the bind in the toml is 0.0.0.0.

And that my friend is all it took! I changed the IP to host.docker.internal and like magic the camera is now showing in BlueIris!

Haha thank you. It is very much appreciated.

**Comment by QuantumEntangledAndy** [comment]
Glad I could help :)
