### ISSUE TITLE
Unable to find glib for the CI windows build

### ISSUE THREAD

**Issue by QuantumEntangledAndy** [thirtythreeforty/neolink#74]
CI Seems to be failing on the windows build by not finding glib2.

Glib should be packaged up by windows with the gstreamer msi in its `bin` directory. I am not sure if we have changed anything that could stop this from being picked up.

Assuming this isn't transient windows errors we could either:

1.  Find out why it is not being found as part of gstreamer bundle
2. Use chocolatlys GTK runtime package and get it from there.

**Comment by twistedddx** [comment]
gstreamer 1.16.2 installed to 
C:\gstreamer\1.0\x86_64\bin

gstreamer 1.18.0 installs to
C:\gstreamer\1.0\msvc_x86_64\bin

Neolink fails to build with glib error when gstreamer is in new path.

Gstreamer installer does update path variable to new location
GSTREAMER_1_0_ROOT_MSVC_X86_64

Manually changing paths path to older C:\gstreamer\1.0\x86_64\bin allows Neolink to build

**Comment by twistedddx** [comment]
I believe gstreamer also changed the variable name from:
GSTREAMER_1_0_ROOT_X86_64
To:
GSTREAMER_1_0_ROOT_MSVC_X86_64

**Comment by QuantumEntangledAndy** [comment]
Hmm our workflow still uses 1.16.2 why would this be a factor?

**Comment by QuantumEntangledAndy** [comment]
The workflow we use also manually sets the PATH already

**Comment by QuantumEntangledAndy** [comment]
For reference here is the code we use for our action

```powershell
$curlgst = Start-Job -ScriptBlock { curl.exe -fsSL "https://gstreamer.freedesktop.org/data/pkg/windows/1.16.2/gstreamer-1.0-devel-msvc-x86_64-1.16.2.msi" -o gstreamer-1.0-devel.msi }
echo "Installing gstreamer-1.0-devel"
Wait-Job $curlgst
msiexec /i gstreamer-1.0-devel.msi /qn /norestart
echo "Updating Environment"
echo "::add-path::C:\gstreamer\1.0\x86_64\bin"
echo "::set-env name=GSTREAMER_1_0_ROOT_X86_64::C:\gstreamer\1.0\x86_64\"
```

**Comment by QuantumEntangledAndy** [comment]
I am not sure we should be using choco and the msi maybe that is causeing issues

**Comment by QuantumEntangledAndy** [comment]
Checking the logs we download the development of msi as 1.16 but choco installs 1.18 on top. I think we should remove the choco and just use the msi

**Comment by QuantumEntangledAndy** [comment]
So I tried to install just via the msi but
```
msiexec /i gstreamer-1.0-devel.msi /qn /norestart
```
Is not installing, I really don't want to have to reinstall my windows VM just for this, but it seems I will need to in order to understand why the msi won't install

**Comment by twistedddx** [comment]
Both of these work for me if I run them as admin, they silently fail if no admin rights.
msiexec /i gstreamer-1.0-msvc-x86_64-1.18.0.msi /qn /norestart
msiexec /i gstreamer-1.0-devel-msvc-x86_64-1.18.0.msi /qn /norestart

Also devel does take about 10 seconds on my machine to be installed. It is 670mb of files that need to be extracted.

**Comment by QuantumEntangledAndy** [comment]
Perhaps that's is why it is silently failing on the building machine, I will look into it

**Comment by twistedddx** [comment]
The installer actually defaults to D:\gstreamer over C:\gstreamer for me also.

**Comment by QuantumEntangledAndy** [comment]
Yes I have been checking to see where it installs two in both C and D in case that happens.

Currently my code looks like this:

```powershell
echo "Downloading gstreamer-1.0-devel"
          Invoke-WebRequest -Uri "https://gstreamer.freedesktop.org/data/pkg/windows/1.16.2/gstreamer-1.0-devel-msvc-x86_64-1.16.2.msi" -OutFile "gstreamer-1.0-devel.msi"
          dir
          echo "Installing gstreamer-1.0-devel"
          $file = Get-ChildItem "gstreamer-1.0-devel.msi"
          $MSIArguments = @(
              "/i"
              ('"{0}"' -f $file.fullname)
              "/qn"
              "/norestart"
              "/L*v"
              $logFile
          )
          Start-Process "msiexec.exe" -ArgumentList $MSIArguments -Wait -NoNewWindow
          echo "Updating Environment"
          echo "::add-path::C:\gstreamer\1.0\x86_64\bin"
          echo "::set-env name=GSTREAMER_1_0_ROOT_X86_64::C:\gstreamer\1.0\x86_64\"
          Get-ChildItem "C:\" | Foreach-Object FullName
          Get-ChildItem "D:\" | Foreach-Object FullName
```

**Comment by QuantumEntangledAndy** [comment]
I am trying to run it in github actions now but it seems to have frozen...

**Comment by QuantumEntangledAndy** [comment]
Alright so current script installs gstreamer from the msi now just got to get it to compile the rust now yay

**Comment by thirtythreeforty** [comment]
The reason I'm using Chocolatey, then the MSI, is that choco installs the main package _plus_ the path setup. When this was originally written, choco didn't have a package for the dev files.

I also neglected to pin the choco-installed version, so choco has started installing 1.18 with the advent of the new release.

The good news is that they now ship both packages. I will switch to simply installing those, and pin the version numbers 'till we're ready to update.

**Comment by thirtythreeforty** [comment]
@QuantumEntangledAndy you say you don't want to use Chocolatey, any reason why?

**Comment by thirtythreeforty** [comment]
Fixed in 6d7b07d

**Comment by QuantumEntangledAndy** [comment]
I was thinking to swap out from choco to avoid this update issue in the future but pinning would work if they have it. Also when I was looking for the packages on choco repo I saw that gstreamer is 1.18 but gstreamer-devel is 1.16 so need to keep at 1.16 until that's updated.

**Comment by QuantumEntangledAndy** [comment]
Anyways that was a fun diversion for the evening learned lots of windows things. I shall close this if it's passing ok :)

**Comment by thirtythreeforty** [comment]
Yep, agreed on all points. I'm glad someone else finds Windows things annoying. Will close!
