### ISSUE TITLE
[Question] IoError / file missing when trying to start Neolink

### ISSUE THREAD

**Issue by cc4005** [thirtythreeforty/neolink#81]
I receive the following when I try to run Neolink from the CLI. Is there a way to know what file is missing? My config file is in the same folder as the neolink pkg. I have gstreamer 64 bit runtime and dev pkgs installed and env variiable set (Win10).

```
[2020-10-12T23:11:02Z INFO  neolink] Neolink 0.3.0 (unknown commit) release
Error: IoError(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })
```

**Comment by thirtythreeforty** [comment]
Sorry you're having trouble. I suspect it can't find your configuration file (and if so, the error message needs improving).

Can you show the command you're running?

**Comment by cc4005** [comment]
Thank you for the reply. As I read it I had a face palm moment. I was trying to run neolink with full path rather than making its directory current. With that change Neolink now starts and connects to the camera. Step 1! Blue Iris is showing connection refused, but I'll continue troubleshooting.
