### ISSUE TITLE
Install and setup on Raspberry Pi

### ISSUE THREAD

**Issue by ioitall** [thirtythreeforty/neolink#98]
**Is your feature request related to a problem? Please describe.**
I see that their is a build for the Raspberry Pi, however I do not see install instructions.

**Describe the solution you'd like**
Is there a place to get the install instructions to get Neolink up and running on raspberry pi so that it auto runs all the time?

**Comment by QuantumEntangledAndy** [comment]
Yes you can follow the instructions in the docs. Check out `docs/unix_service.md` let me know if you get any issues with it.

**Comment by ioitall** [comment]
I believe I was able to install gstreamer however is there anything else
that needs to be installed too before taking these steps in the docs?

**Comment by QuantumEntangledAndy** [comment]
The docs in `docs/unix_setup.md` lists the required plugins. But to summarise this:

```bash
sudo apt install \
  libgstrtspserver-1.0-0 \
  libgstreamer1.0-0 \
  libgstreamer-plugins-bad1.0-0 \
  gstreamer1.0-plugins-good \
  gstreamer1.0-plugins-bad
```

should be enough

**Comment by QuantumEntangledAndy** [comment]
Where you able to get it working?

**Comment by ioitall** [comment]
Yes I got it working like a charm. Thank so much. Sorry I did not say anything. Just been uber busy.
